### ISSUE TITLE
Cannot run example specs - Webpack Compilation Error

### ISSUE THREAD

**Issue by aplaskota** [cypress-io/cypress#8523]
### Current behavior:

I cannot open any example tests. Each try generates the same error
```
Error: Webpack Compilation Error
./cypress/integration/examples/aliasing.spec.js

Module build failed (from C:/user_path/Cypress/Cache/5.1.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):

Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.
```
### Desired behavior:

Example tests should be run and working after Cypress installation

### Test code to reproduce

- Instll Cypress (`npm install cypress --save-dev`)
- Open desktop app (`npx cypress open`)
- Pick up one of the existing example tests
 

### Versions

Node 10.22.0
npm 6.14.6
Cypress 5.1.0
Windows 10
Chrome 85.0.4183.83 (Official Build) (64-bit)

**Comment by nelsongustavo** [comment]
Webpack Compilation Error
./cypress/support/index.js
Module build failed (from /Users/gustavop/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-transform-class-properties' from '/Users/gustavop/code/sst-digital'
Webpack Compilation Error
./cypress/integration/examples/actions.spec.js
Module build failed (from /Users/gustavop/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-transform-class-properties' from '/Users/gustavop/code/sst-digital'

Same here.

**Comment by bcholewinski** [comment]
After upgrading cypress from 4.11 to 5.3 we have the same error in our project.

```
Error: Webpack Compilation Error
./cypress/integration/test.spec.js
Module build failed (from C:/Users/Bartek/AppData/Local/Cypress/Cache/5.3.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\smf\admin\frontend_smf_admin\node_modules\babel-preset-stage-2\lib\index.js
```

**Comment by havenchyk** [comment]
Might be a duplication of https://github.com/cypress-io/cypress/issues/8364

**Comment by jennifer-shehane** [comment]
@aplaskota @nelsongustavo  Is this failing with the example specs that are seeding within your project? Or is this happening in the example specs after cloning the https://github.com/cypress-io/cypress-example-kitchensink repo directly?

If it's within your own project, do you have a `.babelrc` file present in the project? Because it may be a duplicate of #8364 or some other issue. Please provide the contents of this file or any other configuration from you project. Thanks!

**Comment by jjalonso** [comment]
just happened to me,on my project:  yarn add cypress, yarn run cypress open, clicking any spec will show that error.

**Comment by jennifer-shehane** [comment]
@jjalonso Can you provide a repo that we can run to reproduce this error?

**Comment by jjalonso** [comment]
My message was invalid, since i found an issue where i really had two
babel, one in babelrc file, and another babel prop in package.json. then...
not an issue.

**Comment by ralex7** [comment]
I'm having a similar error when trying to run one of my tests on AWS codebuild through my github repo. Here is my error and buildspec files. Any ideas? 
![Screen Shot 2020-11-30 at 3 28 24 PM](https://user-images.githubusercontent.com/52293128/100661995-4d141b00-3322-11eb-93f3-e049a6c19f6f.png)
![Screen Shot 2020-11-30 at 3 36 06 PM](https://user-images.githubusercontent.com/52293128/100662001-50a7a200-3322-11eb-889b-1d94d7e8c4a3.png)

**Comment by sarimarton** [comment]
This, or something similar is happening to me:

```
Error: Webpack Compilation Error
./cypress/integration/examples/actions.spec.js
Module build failed (from /Users/marton.sari/Library/Caches/Cypress/6.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/marton.sari/exempt/portfolium/web/node_modules/babel-preset-es2015/lib/index.js
```

MacOS@10.15.7
Cypress@6.0.1

I can't share the project repo.

**Comment by s4l4x** [comment]
Same issue here in a private repo:

`"cypress": "^6.2.0",`

```Webpack Compilation Error
./cypress/integration/sample_spec.js
Module build failed (from /Users/s4l4x/Library/Caches/Cypress/6.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In .../node_modules/babel-preset-react/lib/index.js```

**Comment by jennifer-shehane** [comment]
Can anyone provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nelsongustavo** [comment]
> @aplaskota @nelsongustavo Is this failing with the example specs that are seeding within your project? Or is this happening in the example specs after cloning the https://github.com/cypress-io/cypress-example-kitchensink repo directly?
> 
> If it's within your own project, do you have a `.babelrc` file present in the project? Because it may be a duplicate of #8364 or some other issue. Please provide the contents of this file or any other configuration from you project. Thanks!

> Can anyone provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Hey guys, it was my .babelrc file...  
![image](https://user-images.githubusercontent.com/1247141/104232802-9bdbc700-542f-11eb-901e-4f6a4d32b420.png)

I was able to fix with this modification...

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/8364

**Comment by AdinaFakih** [comment]
const { should } = require("chai")

Remove the above line from your code, this line maybe on top of you commands.js file
This will fix the error for me

**Comment by pratikraut840** [comment]
Just delete the last two folders i.e. Plugings & supports and see the magic

**Comment by sumayya86** [comment]
@pratikraut840 this solution is perfect. works for me

**Comment by testingy12345** [comment]
Error: Webpack Compilation Error
./cypress/e2e/PageObjectModel.cy.js
Module not found: Error: Can't resolve '../PageObject/LoginPage.js' in 'C:\Users\Dell\CypressAutomation\cypress\e2e'
Looked for and couldn't find the file at the following paths:
[C:\Users\Dell\CypressAutomation\cypress\PageObject\LoginPage.js]
[C:\Users\Dell\CypressAutomation\cypress\PageObject\LoginPage.js.js]
[C:\Users\Dell\CypressAutomation\cypress\PageObject\LoginPage.js.json]
[C:\Users\Dell\CypressAutomation\cypress\PageObject\LoginPage.js.jsx]
[C:\Users\Dell\CypressAutomation\cypress\PageObject\LoginPage.js.mjs]
[C:\Users\Dell\CypressAutomation\cypress\PageObject\LoginPage.js.coffee]
 @ ./cypress/e2e/PageObjectModel.cy.js 3:17-54

**Comment by AtofStryker** [comment]
@testingy12345 are you able to file a separate issue with a reproduction that we can run to recreate the issue?

**Comment by testingy12345** [comment]
> @testingy12345 are you able to file a separate issue with a reproduction that we can run to recreate the issue?

The issue is resolved in today afternoon.

**Comment by prios-mbenyakoub** [comment]
@testingy12345 how did you resolve the issue ?
