### ISSUE TITLE
Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available) when including aws-amplify

### ISSUE THREAD

**Issue by DaveClissold** [cypress-io/cypress#8361]
### Current behavior:
Have just upgraded to version 5.0.0 and it looks like there is a webpack config issue, missing *.mjs support, which is causing the @aws-amplify and graphql libraries from compiling.  This worked in 4.12.1

[aws-amplify/amplify-js#4299](aws-amplify/amplify-js/issues/4299)
[graphql/graphql-js#1272](https://github.com/graphql/graphql-js/issues/1272#issuecomment-377384574)

```
Error: Webpack Compilation Error
./node_modules/graphql/index.mjs 49:0-53:205
Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)
 @ ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js
 @ ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js
 @ ./node_modules/@aws-amplify/pubsub/lib-esm/index.js
 @ ./node_modules/aws-amplify/lib-esm/index.js
 @ ./cypress/support/custom/userLogin.ts
 @ ./cypress/support/custom/index.ts
 @ ./cypress/support/commands.ts
 @ ./cypress/support/index.ts
```

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-291) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
@DaveClissold Can you provide a full example for how you get this error please? Thanks!

**Comment by DaveClissold** [comment]
@jennifer-shehane I have a custom function to login to the AWS Cognito service, which uses the [aws-amplify](https://github.com/aws-amplify/amplify-js) library.

```
import Amplify, { Auth } from 'aws-amplify';


Amplify.configure({
  Auth: {
    region: Cypress.env('AWS_REGION'),
    userPoolId: Cypress.env('AWS_USERPOOLID'),
    userPoolWebClientId: Cypress.env('AWS_USERPOOLWEBCLIENTID'),
  }
})

export const awsLogin = async () => {
  const username = Cypress.env('TEST_USERNAME');
  const password = Cypress.env('TEST_PASSWORD')
  try
    {
      const user = await Auth.signIn(username, password);
      return user
    } 
  catch (error)
    {
      console.log('error signing in', error);
    }
}
```
Aws-amplify relies on graphql queries, whose library 'very kindly' uses .mjs files.

**Comment by liadb** [comment]
Same issue when upgrading to Cypress 5 and using amplify

**Comment by jennifer-shehane** [comment]
I can recreate the error when including aws-amplify:

### Repro

`cypress/support/index.js`

```js
import Amplify from 'aws-amplify'
```

`package.json`

```js
{
  "devDependencies": {
    "aws-amplify": "^3.0.24",
    "cypress": "5.0.0"
  }
}
```

### 4.12.1

The `aws-amplify` takes a really long time to load normally. see https://github.com/cypress-io/cypress/issues/7464

<img width="539" alt="Screen Shot 2020-08-24 at 4 23 48 PM" src="https://user-images.githubusercontent.com/1271364/91031159-3759d000-e626-11ea-81ab-32a707f50093.png">


### 5.0.0

<img width="760" alt="Screen Shot 2020-08-24 at 4 21 06 PM" src="https://user-images.githubusercontent.com/1271364/91031058-109b9980-e626-11ea-923b-cd9ac4092fd2.png">
