### PR TITLE
fix: Fix mjs file support

### LINKED ISSUE #8361: Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available) when including aws-amplify
### Current behavior:
Have just upgraded to version 5.0.0 and it looks like there is a webpack config issue, missing *.mjs support, which is causing the @aws-amplify and graphql libraries from compiling.  This worked in 4.12.1

[aws-amplify/amplify-js#4299](aws-amplify/amplify-js/issues/4299)
[graphql/graphql-js#1272](https://github.com/graphql/graphql-js/issues/1272#issuecomment-377384574)

```
Error: Webpack Compilation Error
./node_modules/graphql/index.mjs 49:0-53:205
Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)
 @ ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js
 @ ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js
 @ ./node_modules/@aws-amplify/pubsub/lib-esm/index.js
 @ ./node_modules/aws-amplify/lib-esm/index.js
 @ ./cypress/support/custom/userLogin.ts
 @ ./cypress/support/custom/index.ts
 @ ./cypress/support/commands.ts
 @ ./cypress/support/index.ts
```

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-291) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #8361

### User facing changelog

- Fixed an issue where .mjs files would error

### Additional Details

The true fix for this is in [@cypress/webpack-batteries-included-preprocessor](https://github.com/cypress-io/cypress-webpack-batteries-included-preprocessor). This bumps its version and adds a test for .mjs files.

Also did some minor refactoring of the plugins e2e spec.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]
This issue has some links in the stack trace to .mjs file, wonder if it's related, but they didn't really give a repro https://github.com/cypress-io/cypress/issues/8373

I manually verified that this fixes the original issue. Tests look good. 👍

**Comment by mustafawm** [comment]
I know this is not the right place to ask, but is there any branch where upgrading to webpack 5 is being tested?

Webpack has progressed to `^5.0.0-rc.3` and  `webpack-preprocessor` seems incompatible with it (some vague error about `Automatic publicPath is not supported in this browser`)

_I tried pulling and upgrading `webpack-preprocessor` locally, but to no avail :(_
