### ISSUE TITLE
Webpack compilation error "TS1110: Type expected" in node_modules/cypress/vue/dist/@vue/test-utils/constants/dom-events.d.ts after upgrade of Cypress from 10.3.0 to 10.3.1 (10.4.0) 

### ISSUE THREAD

**Issue by viktorgogulenko** [cypress-io/cypress#23274]
### Current behavior

After upgrade from 10.3.0 to 10.3.1 and 10.4.0 when we are trying to launch a test, it fails with error:
Error: Webpack Compilation Error
/Path_to_project/node_modules/cypress/vue/dist/@vue/test-utils/constants/dom-events.d.ts
[tsl] ERROR in /Path_to_project/node_modules/cypress/vue/dist/@vue/test-utils/constants/dom-events.d.ts(30,63)
      TS1110: Type expected.

/Path_to_project//node_modules/cypress/vue/dist/@vue/test-utils/constants/dom-events.d.ts
[tsl] ERROR in /Path_to_project//node_modules/cypress/vue/dist/@vue/test-utils/constants/dom-events.d.ts(30,281)
      TS1005: '}' expected.

### Desired behavior

After upgrade we are still able to launch and execute our e2e tests

### Test code to reproduce

node -v
v14.18.1

npm -v
6.14.15

### Cypress Version

10.4.0

**Comment by nagash77** [comment]
@viktorgogulenko Unfortunately the provided information is insufficient for us to properly debug this issue.  Can you provide more detail (debug logs, example spec files, a repo demonstrating the issue) that would allow us to reproduce the problem internally?

**Comment by viktorgogulenko** [comment]
I'm not sure that I'll be able to provide a repo, but will try to find a solution. Just FYI - as soon as I removed `/node_modules/cypress/vue/` folder - tests started to work again. So this is definitely related to some changes with this specific part from 10.3.0 to 10.3.1

**Comment by rockindahizzy** [comment]
Hey @viktorgogulenko, does [this PR](https://github.com/cypress-io/cypress/pull/23299) seem related to the issue you are having?

**Comment by viktorgogulenko** [comment]
Hi @rockindahizzy. Not sure. I have a feeling that we are using an old version of typescript and after upgrade of Cypress it became broken. For now as a workaround to make it working again I've excluded vue folder from tsconfig.json and started to work:
```
"exclude": [
    "node_modules",
    "../node_modules/cypress/vue" // there is some issue with this folder  (see https://github.com/cypress-io/cypress/issues/23274)
  ],
```
and in parallel we are trying to update typescript for our project to the latest one.

**Comment by rockindahizzy** [comment]
@viktorgogulenko, sounds good.  That PR I referenced was release in `10.5.0` yesterday. Are you able to upgrade to `10.5` and see if that resolves your issue?

**Comment by viktorgogulenko** [comment]
@rockindahizzy just tried to upgrade from 10.3.0 to 10.5.0 - still the same problem for us. 😔

**Comment by rockindahizzy** [comment]
Thanks for trying, sorry it didn't work. What version of typescript are you currently using? I will see if I can recreate in a plain typescript project.

**Comment by viktorgogulenko** [comment]
@rockindahizzy really old one - 3.8.3. We've tried to update to the latest 4.7.4 but there are so many issues with dependencies appeared that we will definitely need some time to fix all that things.

**Comment by rockindahizzy** [comment]
Thanks for that info! Are you able to provide your `tsconfig.json` and `cypress.config.ts` files?

**Comment by viktorgogulenko** [comment]
tsconfig.json:
```
{
  "compileOnSave": false,
  "exclude": [
    "node_modules",
    "../node_modules/cypress/vue" // there is some issue with this folder (see https://github.com/cypress-io/cypress/issues/23274)
  ],
  "compilerOptions": {
    "sourceMap": false,
    "allowJs": true,
    "target": "es2015",
    "types": ["cypress", "node", "@testing-library/cypress", "cypress-real-events"],
    "baseUrl": "./",
    "downlevelIteration": true,
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "outDir": "./dist/out-tsc",
    "declaration": false,
    "module": "es2020",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "paths": {
      "#cy/*": ["./*"],
    },
    "typeRoots": [
      "node_modules/@types",
      "./types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],

  },
  "include": ["integration/**/*.ts", "support/*.ts", "../node_modules/cypress", "./cypress.config.ts"],

}
```
cypress.config.ts:
```
import { defineConfig } from 'cypress';

require('../utils/handleParameters')();
const path = require('path');
const e2eCodeCoverage = require('@cypress/code-coverage/task');
const { addMatchImageSnapshotPlugin } = require('cypress-image-snapshot/plugin');
const webpack = require('@cypress/webpack-preprocessor');
const pdf = require('pdf-parse');
const xlsx = require('xlsx');

const {
  ApiLayer,
  Gx2Simulator,
  HubSimulator,
  Io4Simulator,
  A4xSimulator,
  IoBankBuilder
} = require('core-simulator');

export default defineConfig({
  e2e: {
    projectId: 'j4b11p',
    baseUrl: 'http://localhost:4200',
    chromeWebSecurity: false,
    specPattern: 'integration/**/*.spec.{js,jsx,ts,tsx}',
    viewportHeight: 960,
    viewportWidth: 1280,
    defaultCommandTimeout: 30000,
    watchForFileChanges: false,
    trashAssetsBeforeRuns: true,
    videoUploadOnPasses: true,
    taskTimeout: 180000,
    fixturesFolder: './fixtures',
    screenshotsFolder: './screenshots',
    videosFolder: './videos',
    supportFile: './support/e2e.ts',
    fileServerFolder: './',
    retries: {
      runMode: 2,
      openMode: 0
    },
    env: {
      prepareBrowserForSnapshotTesting: false,
      coverage: false,
      readFileTimeout: 30000,
      flakyQuarantine: false,
    },
    setupNodeEvents(on, config) {
      addMatchImageSnapshotPlugin(on, config);
      const serverPath = config.baseUrl;
      const email = process.env.ADMIN_EMAIL;
      const pw = process.env.ADMIN_PASS;
      let api;
      let gx2;
      let hub;
      let io4;
      let ioBank;
      let a4x;
      config.env.E2E_INSTANCE = process.env.E2E_INSTANCE;
      config.env.defaultEmail = email;
      config.env.defaultPassword = pw;
      config.env.coverage = process.env.E2E_TESTS_COVERAGE === 'true';
      config.env.flakyQuarantine = process.env.FLAKY_QUARANTINE;

      const initSims = () => {
        if (gx2) { gx2.stopSimulator(); }
        if (hub) { hub.stopSimulator(); }
        if (io4) { io4.stopSimulator(); }
        if (a4x) { a4x.stopSimulator(); }
        api = new ApiLayer(serverPath, email, pw);
        gx2 = new Gx2Simulator(serverPath, email, pw);
        hub = new HubSimulator(serverPath, email, pw);
        io4 = new Io4Simulator(serverPath, email, pw);
        a4x = new A4xSimulator(serverPath, email, pw);
        ioBank = new IoBankBuilder(serverPath, email, pw);
      };
      initSims();

      on('before:spec', async () => {
        initSims();
      });
      e2eCodeCoverage(on, config);
      // `on` is used to hook into various events Cypress emits
      // `config` is the resolved Cypress config
      on('task', {
        simulatorApi([methodName, ...params]) {
          return api[methodName](...params);
        },

        gx2Sim([methodName, ...params]) {
          return gx2[methodName](...params);
        },

        hubSim([methodName, ...params]) {
          return hub[methodName](...params);
        },

        a4xSim([methodName, ...params]) {
          return a4x[methodName](...params);
        },

        io4Sim([methodName, ...params]) {
          return io4[methodName](...params);
        },

        ioBank([methodName, ...params]) {
          return ioBank[methodName](...params);
        },

        getPdfContent(filename) {
          return pdf(filename);
        },

        readExcel(filename) {
          return xlsx.readFile(filename);
        }

      });

      // Define webpack alias for cypress
      on('file:preprocessor', webpack({
        watchOptions: {},
        webpackOptions: {
          module: {
            rules: [
              {
                test: /\.ts$/,
                exclude: [/node_modules/],
                use: [{ loader: 'ts-loader' }]
              }
            ]
          },
          resolve: {
            extensions: ['.ts', '.js'],
            alias: {
              '#cy': path.resolve(__dirname, './'),
              '#root': path.resolve(__dirname, '../'),
            }
          }
        }
      }));

      // eslint-disable-next-line consistent-return
      on('before:browser:launch', (browser, launchOptions) => {
        if (config.env.prepareBrowserForSnapshotTesting) {
          if (browser.name === 'chrome' && browser.isHeaded) {
            // fullPage screenshot size is 1400x1200 on non-retina screens
            // and 2800x2400 on retina screens
            launchOptions.args.push('--window-size=1400,1200');

            // force screen to be non-retina (1400x1200 size)
            launchOptions.args.push('--force-device-scale-factor=1');

            // force screen to be retina (2800x2400 size)
            // launchOptions.args.push('--force-device-scale-factor=2')
          }

          if (browser.family === 'chromium' && browser.name !== 'electron') {
            launchOptions.args.push('--start-fullscreen');
          }
          return launchOptions;
        }
      });

      return config;
    }
  }
});
```

**Comment by mike-plummer** [comment]
Hi @viktorgogulenko , thanks for providing your configs! I set up a fresh Cypress project using Typescript 3.8.3 and incorporated as much of your setup from above as I could (I had to strip out your sim mocks), but unfortunately was not able to reproduce the issue you described. It's possible there's a difference in our project structure or dependencies (or a million other things 😁 ) that I'm not matching locally. If you aren't able to make a reproducible example available then we may have to see if debug logs can give us a hint. Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and attach the logs here?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
