### ISSUE TITLE
Playground Error: Webpack Compilation Error when opening a test file

### ISSUE THREAD

**Issue by chaussen** [cypress-io/cypress#28072]
### Current behavior

After I upgraded Cypress to 13.3.1 and Chrome browser to 118, my test file cannot open in the Selector Playground.
The page shows error:

Error: Webpack Compilation Error
Module not found: Error: Package path ./types/lodash is not exported from package C:\xxx\node_modules\cypress (see exports field in C:\xxx\node_modules\cypress\package.json)

### Desired behavior

It should continue to open the test file and run tests

### Test code to reproduce

Open a test spec file in playground

### Cypress Version

^13.2.0

### Node version

20.5.1

### Operating System

Windows 11

### Debug Logs

```shell
Error: Webpack Compilation Error
Module not found: Error: Package path ./types/lodash is not exported from package C:\xxx\node_modules\cypress (see exports field in C:\xxx\node_modules\cypress\package.json)
```

### Other

Typescript has trouble understanding Lodash methods like _.map

**Comment by jennifer-shehane** [comment]
We upgraded Webpack from 4 to 5 in 12.17.4, so it's likely related to that. https://docs.cypress.io/guides/references/changelog#12-17-4
