### ISSUE TITLE
Cypress 10.10 not working in macOS 10.12.6, requires at least 10.13

### ISSUE THREAD

**Issue by chekobil** [cypress-io/cypress#24314]
### Current behavior

If the installation is made through `npm` you get version 10.10, the Cypress.app installed with latest version updates Electron.framework to v21 that requires at least macOS 10.13, so the app is not compatible and running `npx cypress open` crashes.
Documentation says that Cypress is compatible from macOS 10.9

### Desired behavior

Installation shows a compatibility error

### Test code to reproduce

on macOSX 10.12.6
`npm install -D cypress`
`npx cypress open`

### Cypress Version

10.10

### Node version

16.9.1

### Operating System

macOS 10.12.6

### Debug Logs

```shell
It looks like this is your first time using Cypress: 10.10.0


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

dyld: Symbol not found: _kCVImageBufferTransferFunction_sRGB
Referenced from: /Users/kobino/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework (which was built for Mac OS X 10.13)
Expected in: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
in /Users/kobino/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework

----------

Platform: darwin-x64 (16.7.0)
Cypress Version: 10.10.0
```

**Comment by iravella** [comment]
macOS 11.7, npm installation.

```
It looks like this is your first time using Cypress: 10.10.0


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Users/user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/MacOS/Cypress
Reason: no suitable image found.  Did find:
/Users/user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
/Users/user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

----------

Platform: darwin-x64 (20.6.0)
Cypress Version: 10.10.0
```

**Comment by chekobil** [comment]
By the way Cypress 10.9 works fine, at least on macOS 10.12.6, because it works with Electron v19

**Comment by nagash77** [comment]
@chekobil Thank you for pointing out where our documentation needs updating.  The upgrade for electron is required for Cypress 10.10 as it contains changes that fixed firefox regressions that the electron team introduced.  I am closing this issue and will be opening an issue with our documentation team to update our supported OS versions.
