### ISSUE TITLE
Unable to find cypress-multi-reporters

### ISSUE THREAD

**Issue by LinF001** [cypress-io/cypress#24616]
### Current behavior

Error loading the reporter: cypress-multi-reporters 

this is my `cypress.config.js` look like

module.exports = defineConfig({
  projectId: 'pxk123',
  screenshotOnRunFailure: true,
  video: false,
  chromeWebSecurity: false,
  viewportWidth: 1024,
  viewportHeight: 768,
  reporter: 'cypress-multi-reporters',
  reporterOptions: {
    configFile: 'reporter-config.js',
  }
})

this is my package look like:

"devDependencies": {
    "@reportportal/agent-js-cypress": "^5.1.0",
    "axe-core": "^4.5.1",
    "cypress": "^11.0.0",
    "cypress-audit": "^1.1.0",
    "cypress-axe-core": "^2.0.0",
    "cypress-cucumber-preprocessor": "^4.3.1",
    "cypress-multi-reporters": "^1.6.1",
    "eslint": "^8.27.0",
    "eslint-plugin-cypress": "^2.12.1",
    "mocha": "^10.1.0",
    "mocha-junit-reporter": "^2.1.1",
    "mochawesome": "^7.1.3",
    "mochawesome-report-generator": "^6.2.0",
    "multiple-cucumber-html-reporter": "^3.0.1",
    "request": "^2.88.2",
    "jwt-decode": "^3.1.2"
  }

### Desired behavior

I was using cypress 10.11.0 and it works fine with the cypress-multi-reporter. 

After I updated to 11.0.0 the reporter can not be found. 

### Test code to reproduce

Error loading the reporter: cypress-multi-reporters

We searched for the reporter in these paths:

 - /Users/Documents/AD_QA/swampy-ui-test/cypress-multi-reporters
 - /Users/Documents/AD_QA/swampy-ui-test/node_modules/cypress-multi-reporters

Learn more at https://on.cypress.io/reporters

Error: Cannot find module 'mocha-7.0.1'
Require stack:
- /Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at PackherdModuleLoader._tryResolveFilename (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:645:32)
    at PackherdModuleLoader._resolvePaths (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:491:31)
    at PackherdModuleLoader.tryResolve (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:313:40)
    at resolve (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/require.js:125:33)
    at require.resolve (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/v8-snapshot-require/dist/snapshot-require.js:216:28)
    at customRequire.resolve (<embedded>:2809:961257)
    at <embedded>:2755:13102
    at i._load (<embedded>:2750:54101)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/Documents/AD_QA/swampy-ui-test/node_modules/cypress-multi-reporters/lib/MultiReporters.js:13:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load [as origLoad] (node:electron/js2c/asar_bundle:5:13339)
    at PackherdModuleLoader.tryLoad (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:432:30)
    at Module._load (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/require.js:87:74)
    at i._load (<embedded>:2750:54140)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/Documents/AD_QA/swampy-ui-test/node_modules/cypress-multi-reporters/index.js:3:24)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load [as origLoad] (node:electron/js2c/asar_bundle:5:13339)
    at PackherdModuleLoader.tryLoad (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:432:30)
    at customRequire (<embedded>:2809:960157)
    at S.loadReporter (<embedded>:2755:19452)
    at P.initializeReporter (<embedded>:2802:336581)
    at P.startWebsockets (<embedded>:2802:336891)
    at P.open (<embedded>:2802:335033)
    at async v.create (<embedded>:2802:347432)
    at async O (<embedded>:2802:421364)
    at async W (<embedded>:2802:432780)

### Cypress Version

11.0.0

### Node version

v18.4.0

### Operating System

macOS 12.6

### Debug Logs

```shell
Error loading the reporter: cypress-multi-reporters

We searched for the reporter in these paths:

 - /Users/Documents/AD_QA/swampy-ui-test/cypress-multi-reporters
 - /Users/Documents/AD_QA/swampy-ui-test/node_modules/cypress-multi-reporters

Learn more at https://on.cypress.io/reporters

Error: Cannot find module 'mocha-7.0.1'
Require stack:
- /Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at PackherdModuleLoader._tryResolveFilename (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:645:32)
    at PackherdModuleLoader._resolvePaths (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:491:31)
    at PackherdModuleLoader.tryResolve (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:313:40)
    at resolve (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/require.js:125:33)
    at require.resolve (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/v8-snapshot-require/dist/snapshot-require.js:216:28)
    at customRequire.resolve (<embedded>:2809:961257)
    at <embedded>:2755:13102
    at i._load (<embedded>:2750:54101)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/Documents/AD_QA/swampy-ui-test/node_modules/cypress-multi-reporters/lib/MultiReporters.js:13:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load [as origLoad] (node:electron/js2c/asar_bundle:5:13339)
    at PackherdModuleLoader.tryLoad (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:432:30)
    at Module._load (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/require.js:87:74)
    at i._load (<embedded>:2750:54140)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/Documents/AD_QA/swampy-ui-test/node_modules/cypress-multi-reporters/index.js:3:24)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load [as origLoad] (node:electron/js2c/asar_bundle:5:13339)
    at PackherdModuleLoader.tryLoad (/Users/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:432:30)
    at customRequire (<embedded>:2809:960157)
    at S.loadReporter (<embedded>:2755:19452)
    at P.initializeReporter (<embedded>:2802:336581)
    at P.startWebsockets (<embedded>:2802:336891)
    at P.open (<embedded>:2802:335033)
    at async v.create (<embedded>:2802:347432)
    at async O (<embedded>:2802:421364)
    at async W (<embedded>:2802:432780)
```

### Other

N/A

**Comment by LinF001** [comment]
someone already posted. https://github.com/cypress-io/cypress/issues/24607

**Comment by monicadevi** [comment]
Error loading the reporter: cypress-multi-reporter

We searched for the reporter in these paths:

 - D:\Workspace\Cypress\TestCyT\cypress-multi-reporter
 - D:\Workspace\Cypress\TestCyT\node_modules\cypress-multi-reporter

Learn more at https://on.cypress.io/reporters

Error: Cannot find module 'D:\Workspace\Cypress\TestCyT\node_modules\cypress-multi-reporter'
Require stack:
- C:\Users\monica.devi\AppData\Local\Cypress\Cache\13.6.4\Cypress\resources\app\packages\server\lib\reporter.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)       
    at n._resolveFilename (node:electron/js2c/browser_init:2:117603)
    at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:791898)
    at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:788688)    
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:786731)
    at Function.<anonymous> (evalmachine.<anonymous>:1:797621)
    at d._load (<embedded>:4452:29351)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at A.loadReporter (<embedded>:4457:21800)
    at C.initializeReporter (<embedded>:4504:27124)
    at C.startWebsockets (<embedded>:4504:27428)
    at C.open (<embedded>:4504:25725)
    at async v.create (<embedded>:4504:40018)
    at async O (<embedded>:4504:128912)
    at async W (<embedded>:4504:141735)
 
I am getting this error with latest cypress version, any solutions

**Comment by Omar-Mohamed-procore** [comment]
same
