### ISSUE TITLE
Cypress fails to start with cannot find module error

### ISSUE THREAD

**Issue by gciltaru** [cypress-io/cypress#26507]
### Current behavior

Cypress fails to start with `Cannot find module './start-cypress'` error when verifying/running cypress@12.6.0(up until the 12.9.0). 

```
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

2023-04-14T17:12:40.934Z cypress:snapshot:info Caching 4272, defining 5376 modules! Using cache
2023-04-14T17:12:40.935Z cypress:snapshot:debug initializing packherd require
Error: Cannot find module './start-cypress'
Require stack:
- /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc
at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:735006)
at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:731827)
at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:729870)
at Function._load (evalmachine.<anonymous>:1:740659)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at i (/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/index.js:1:2232)
at startCypress (evalmachine.<anonymous>:1:761733)
at evalmachine.<anonymous>:1:761993 {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc'
]
}

----------

Platform: darwin-arm64 (22.4.0)
Cypress Version: 12.6.0
```

### Debug logs

```Text
ciltaru @ georges-mbp-2 ➜  /Users/ciltaru/Development/cypress-test DEBUG=cypress:* npx cypress install --force
  cypress:cli:cli cli starts with arguments ["/Users/ciltaru/.nvm/versions/node/v16.14.2/bin/node","/Users/ciltaru/Development/cypress-test/node_modules/.bin/cypress","install","--force"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli parsed cli options { force: true } +150ms
  cypress:cli installing with options {"force":true} +0ms
  cypress:cli detecting arch { osPlatform: 'darwin', osArch: 'arm64' } +1ms
  cypress:cli version in package.json is 12.6.0, version to install is 12.6.0 +1ms
  cypress:cli Reading binary package.json from: /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/package.json +0ms

Cypress 12.6.0 is installed in /Users/ciltaru/Library/Caches/Cypress/12.6.0

  cypress:cli performing force install over existing binary +5ms
  cypress:cli checking local file /Users/ciltaru/12.6.0 cwd /Users/ciltaru/Development/cypress-test +1ms
  cypress:cli Cypress already installed at /Users/ciltaru/Library/Caches/Cypress/12.6.0 +1ms
  cypress:cli but the installation was forced +0ms
  cypress:cli preparing to download and unzip version  12.6.0 to path /Users/ciltaru/Library/Caches/Cypress/12.6.0 +0ms
Installing Cypress (version: 12.6.0)


  cypress:cli needed Cypress version: 12.6.0 +0ms
  cypress:cli source url https://download.cypress.io/desktop/12.6.0?platform=darwin&arch=arm64 +0ms
  cypress:cli downloading cypress.zip to "/var/folders/pg/y87f3pwj6xn09c099s08qjk80000gn/T/cypress-60553.zip" +0ms
  cypress:cli Downloading package {
  url: 'https://download.cypress.io/desktop/12.6.0?platform=darwin&arch=arm64',
  proxy: null,
  downloadDestination: '/var/folders/pg/y87f3pwj6xn09c099s08qjk80000gn/T/cypress-60553.zip'
} +1ms
  cypress:cli expected file size 84 +269ms
  cypress:cli redirect version: 12.6.0 +1ms
  cypress:cli redirect url: https://cdn.cypress.io/desktop/12.6.0/darwin-arm64/cypress.zip +0ms
  cypress:cli Downloading package {
  url: 'https://cdn.cypress.io/desktop/12.6.0/darwin-arm64/cypress.zip',
  proxy: null,
  downloadDestination: '/var/folders/pg/y87f3pwj6xn09c099s08qjk80000gn/T/cypress-60553.zip'
} +0ms
  cypress:cli expected checksum cc86890f3b43ae2277a79dee36e8ed29090b659ef849d2cb4e3401e49e14ee3bd3eea3ad20cc93027602bae0bb555be42151d81d4e771e891f186ab404ff784d +95ms
⠏  Downloading Cypress      98% 0s
  cypress:cli downloading finished +7s
⠸  Downloading Cypress      98% 0s
  cypress:cli downloaded file has the expected checksum and size ✅ +386ms
  cypress:cli verified +1ms
✔  Downloaded Cypress
  cypress:cli:unzip removing existing unzipped binary /Users/ciltaru/Library/Caches/Cypress/12.6.0 +0ms
  cypress:cli:unzip unzipping from /var/folders/pg/y87f3pwj6xn09c099s08qjk80000gn/T/cypress-60553.zip +2s
  cypress:cli:unzip into /Users/ciltaru/Library/Caches/Cypress/12.6.0 +0ms
  cypress:cli:unzip zipFile entries count 20939 +2ms
✔  Downloaded Cypress
✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation /Users/ciltaru/Library/Caches/Cypress/12.6.0

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

ciltaru @ georges-mbp-2 ➜  /Users/ciltaru/Development/cypress-test DEBUG=cypress:* npx cypress verify
  cypress:cli:cli cli starts with arguments ["/Users/ciltaru/.nvm/versions/node/v16.14.2/bin/node","/Users/ciltaru/Development/cypress-test/node_modules/.bin/cypress","verify"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli parsed cli options {} +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/MacOS/Cypress +1ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app +0ms
  cypress:cli Reading binary package.json from: /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/package.json +0ms
  cypress:cli Found binary version 12.6.0 installed in: /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app +2ms
  cypress:cli could not read binary_state.json file at "/Users/ciltaru/Library/Caches/Cypress/12.6.0/binary_state.json" +3ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +2ms
  cypress:cli force verify +0ms
  cypress:cli running binary verification check 12.6.0 +0ms


  cypress:cli clearing out the verified version +2ms
  cypress:cli needs Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +0ms
  cypress:cli disabling Electron sandbox +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/MacOS/Cypress +0ms
  cypress:cli smoke test command: /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=25 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command failed with exit code 1: /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=25
2023-04-14T17:12:40.934Z cypress:snapshot:info Caching 4272, defining 5376 modules! Using cache
2023-04-14T17:12:40.935Z cypress:snapshot:debug initializing packherd require
Error: Cannot find module './start-cypress'
Require stack:
- /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:735006)
    at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:731827)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:729870)
    at Function._load (evalmachine.<anonymous>:1:740659)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at i (/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/index.js:1:2232)
    at startCypress (evalmachine.<anonymous>:1:761733)
    at evalmachine.<anonymous>:1:761993 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc'
  ]
}
    at makeError (/Users/ciltaru/Development/cypress-test/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/ciltaru/Development/cypress-test/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=25',
  command: '/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=25',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '2023-04-14T17:12:40.934Z cypress:snapshot:info Caching 4272, defining 5376 modules! Using cache\n' +
    '2023-04-14T17:12:40.935Z cypress:snapshot:debug initializing packherd require\n' +
    "Error: Cannot find module './start-cypress'\n" +
    'Require stack:\n' +
    '- /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc\n' +
    '    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)\n' +
    '    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)\n' +
    '    at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:735006)\n' +
    '    at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:731827)\n' +
    '    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:729870)\n' +
    '    at Function._load (evalmachine.<anonymous>:1:740659)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1012:19)\n' +
    '    at i (/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/index.js:1:2232)\n' +
    '    at startCypress (evalmachine.<anonymous>:1:761733)\n' +
    '    at evalmachine.<anonymous>:1:761993 {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: [\n' +
    "    '/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc'\n" +
    '  ]\n' +
    '}',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +2s
  cypress:cli error message: 2023-04-14T17:12:40.934Z cypress:snapshot:info Caching 4272, defining 5376 modules! Using cache
2023-04-14T17:12:40.935Z cypress:snapshot:debug initializing packherd require
Error: Cannot find module './start-cypress'
Require stack:
- /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:735006)
    at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:731827)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:729870)
    at Function._load (evalmachine.<anonymous>:1:740659)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at i (/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/index.js:1:2232)
    at startCypress (evalmachine.<anonymous>:1:761733)
    at evalmachine.<anonymous>:1:761993 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc'
  ]
} +1ms

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

2023-04-14T17:12:40.934Z cypress:snapshot:info Caching 4272, defining 5376 modules! Using cache
2023-04-14T17:12:40.935Z cypress:snapshot:debug initializing packherd require
Error: Cannot find module './start-cypress'
Require stack:
- /Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc
at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:735006)
at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:731827)
at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:729870)
at Function._load (evalmachine.<anonymous>:1:740659)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at i (/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/index.js:1:2232)
at startCypress (evalmachine.<anonymous>:1:761733)
at evalmachine.<anonymous>:1:761993 {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/Users/ciltaru/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/index.jsc'
]
}

----------

Platform: darwin-arm64 (22.4.0)
Cypress Version: 12.6.0
```

### Cypress Version

12.6.0

### Node version

v16.14.2

### Package Manager

npm

### Package Manager Version

8.5.0

### Operating system

Linux

### Operating System Version

13.3.1

### Other

Apple M1 Max chip

**Comment by jordanpowell88** [comment]
@jordanpowell88. This seams like a dependency issue in the project itself. Are you able to provide a reproducible example so we can investigate further?

**Comment by gciltaru** [comment]
The steps that I use to reproduce on my machine:
```
mkdir cypress-test && cd cypress-test
npm init -y
npm install cypress@12.6.0 # or npm install cypress
npx cypress cache clear
npx cypress install
DEBUG=cypress:* npx cypress verify
```

The package.json content is:
```
{
  "name": "cypress-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cypress": "^12.6.0"
  }
}
```

**Comment by gciltaru** [comment]
Last version that works on my machine is `10.11.0`.

On `11.0.0` I get:

```
Cypress verification timed out.

This command failed with the following output:

/Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=573

----------

2023-04-17T20:06:40.193Z cypress:snapshot:info Caching 2978, defining 3917 modules! Using cache
2023-04-17T20:06:40.194Z cypress:snapshot:debug initializing packherd require
(node:62270) UnhandledPromiseRejectionWarning: Error: Cannot find module './lib/util/patch-fs'
Require stack:
- /Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/server-entry.js
- /Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/index.js
- /Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/index.js
-
at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
at PackherdModuleLoader._tryResolveFilename (/Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:645:32)
at PackherdModuleLoader._resolvePaths (/Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:491:31)
at PackherdModuleLoader.tryLoad (/Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:421:40)
at Module._load (/Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/require.js:87:74)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/server-entry.js:1:21)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
(Use `Cypress --trace-warnings ...` to show where the warning was created)
(node:62270) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
objc[62271]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x248b4efe0) and /Users/ciltaru/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10561a978). One of the two will be used. Which one is undefined.

----------

Platform: darwin-arm64 (22.4.0)
Cypress Version: 11.0.0
```

**Comment by warrensplayer** [comment]
@gciltaru I am able to follow your steps and receive a successful result to the the `npx cypress verify` command.  Is this only happening on your work computer?  Are you able to ask someone else at your company to run the same commands?

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by gciltaru** [comment]
Hi,

I found the issue with my local environment. 

I had defined the `PROJECT_BASE_DIR` environment variable, for a different purpose, which I think conflicted with cypress (https://github.com/cypress-io/cypress/blob/develop/packages/server/hook-require.js#L4).

After I removed this environment variable, cypress worked as expected.

Thanks,
George.
