### ISSUE TITLE
11.0.0 `cypress run` -> `Error: Cannot find module 'mocha-7.0.1'`

### ISSUE THREAD

**Issue by jiadesen** [cypress-io/cypress#24607]
### Current behavior

When I upgraded to 11.0.0, I ran `cypress run` as usual, and I got an error `Error: Cannot find module 'mocha-7.0.1'`

### Test code to reproduce

const { defineConfig } = require('cypress')

module.exports = defineConfig({
  reporter: 'mochawesome',
  reporterOptions: {
    reportDir: 'cypress/results',
    overwrite: false,
    html: false,
    json: true
  }
})

### Cypress Version

11.0.0

### Node version

v16.18.0

### Operating System

macOS 13.0

### Debug Logs

```shell
[1] Error loading the reporter: mochawesome
[1] 
[1] We searched for the reporter in these paths:
[1] 
[1]  - /Users/xxx/project/mochawesome
[1]  - /Users/xxx/project/node_modules/mochawesome
[1] 
[1] Learn more at https://on.cypress.io/reporters
[1] 
[1] Error: Cannot find module 'mocha-7.0.1'
[1] Require stack:
[1] - /Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
[1]     at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
[1]     at PackherdModuleLoader._tryResolveFilename (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:645:32)
[1]     at PackherdModuleLoader._resolvePaths (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:491:31)
[1]     at PackherdModuleLoader.tryResolve (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:313:40)
[1]     at resolve (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/require.js:125:33)
[1]     at require.resolve (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/v8-snapshot-require/dist/snapshot-require.js:216:28)
[1]     at customRequire.resolve (<embedded>:2809:961257)
[1]     at <embedded>:2755:13102
[1]     at i._load (<embedded>:2750:54101)
[1]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[1]     at require (node:internal/modules/cjs/helpers:102:18)
[1]     at Object.<anonymous> (/Users/xxx/project/node_modules/.pnpm/mochawesome@7.1.3_mocha@10.1.0/node_modules/mochawesome/src/mochawesome.js:1:14)
[1]     at Module._compile (node:internal/modules/cjs/loader:1120:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
[1]     at Module.load (node:internal/modules/cjs/loader:988:32)
[1]     at Module._load (node:internal/modules/cjs/loader:829:12)
[1]     at c._load [as origLoad] (node:electron/js2c/asar_bundle:5:13339)
[1]     at PackherdModuleLoader.tryLoad (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:432:30)
[1]     at customRequire (<embedded>:2809:960157)
[1]     at S.loadReporter (<embedded>:2755:19452)
[1]     at P.initializeReporter (<embedded>:2802:336581)
[1]     at P.startWebsockets (<embedded>:2802:336891)
[1]     at P.open (<embedded>:2802:335033)
[1]     at async v.create (<embedded>:2802:347432)
[1]     at async O (<embedded>:2802:421364)
[1]     at async W (<embedded>:2802:432780)
```

**Comment by jiadesen** [comment]
Installing `mocha-7.0.1` still reports this error

**Comment by kryshenp** [comment]
we also have the same issue after cypress updated to 11.0.0.
Our configuration is the same as mentioned in the description.

**Comment by kimberley2310** [comment]
Same issue here, we didn't change anything in our configuration. 
The pipeline started our cypress run for the first time with version 11 and we have the same error.

Locally I was still on version 10 of cypress -> no problems there
Updated locally to version 11 -> same problem

We use 'cypress-multi-reports': 
```
reporter: 'cypress-multi-reporters',
  reporterOptions: {
    reporterEnabled: 'mocha-junit-reporter',
    mochaJunitReporterReporterOptions: {
      mochaFile: 'reports/cypress/xml/e2e-test-results-[hash].xml',
    },
  },
```

**Comment by aliaksei-liauchuk-incountry** [comment]
I have same issue

**Comment by emilyrohrbough** [comment]
We are actively investigating the issue.

**Comment by LinF001** [comment]
The Same issue for me.

**Comment by maslowivan** [comment]
same

**Comment by xometa** [comment]
Same issue

**Comment by atmullan** [comment]
Similar issue only it was modules related to babel which I don't use, tried various npm solutions. Downgrading cypress to previous version was only solution.

**Comment by ryanthemanuel** [comment]
> Similar issue only it was modules related to babel which I don't use, tried various npm solutions. Downgrading cypress to previous version was only solution.

@atmullan, that issue sounds like https://github.com/cypress-io/cypress/issues/24611. Both of these will be fixed with #24630.

**Comment by mjhenkes** [comment]
Released in [11.0.1](https://on.cypress.io/changelog#11-0-1).

This comment thread has been locked. If you are still experiencing this issue after upgrading to
Cypress v11.0.1, please open a new issue.

**Comment by LhFS** [comment]
It seems that this problem is back on Cypress 13+. I am using 13.16.0, and I am able to reproduce the same issue.

**Comment by jennifer-shehane** [comment]
@LhFS Could you specify the error you're seeing and provide a reproducible example?

Could you also try our latest version and let us know if this is still an issue?

**Comment by LhFS** [comment]
Hi @jennifer-shehane 

The error is actually the same as this ticket description

```
Error loading the reporter: mocha-simple-html-reporter

We searched for the reporter in these paths:

 - /Users/luanhenrique/Documents/xxx/xxx/xxx/xxx/mocha-simple-html-reporter
 - /Users/luanhenrique/Documents/xxx/xxx/xxx/xxx/node_modules/mocha-simple-html-reporter

Learn more at https://on.cypress.io/reporters

Error: Cannot find module '/Users/luanhenrique/Documents/sr-multipackage/xx/xx/xx/node_modules/mocha-simple-html-reporter'
Require stack:
- /Users/luanhenrique/Library/Caches/Cypress/13.16.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:116118)
    at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:760372)
    at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:757162)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755205)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at A.loadReporter (<embedded>:2975:21800)
    at C.initializeReporter (<embedded>:3028:27000)
    at C.startWebsockets (<embedded>:3028:27304)
    at C.open (<embedded>:3028:25601)
    at async v.create (<embedded>:3028:40000)
    at async L (<embedded>:3028:79238)
    at async J (<embedded>:3028:93355)
```

I tested with the latest version of Cypress, and I could see the error. Also, I've cleaned up the npm cache, deleted the node_modules folder, and verified the directory where I installed the reporter. 

To reproduce this, using the latest version of Cypress, I installed the mocha-simple-html-reporter using npm, set up everything as per the reporter's documentation, and ran the test. On that occasion, I was running the component tests, then I got the error above.
