### ISSUE TITLE
TypeScript: versioned types are not used

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#8009]
### Current behavior:

Possibly a regression from https://github.com/cypress-io/cypress/pull/7352

Given:

```ts
import { SinonMatcher } from 'cypress/types/sinon';

type F = sinon.SinonSpyCall<number, string>;
```

This errors with `Type 'SinonSpyCall' is not generic.`.

If we look at the type definition, we can see it is not generic. **However**, [there is a generic version inside the `ts3.1` folder](https://unpkg.com/cypress@4.10.0/types/sinon/ts3.1/index.d.ts). For some reason TypeScript is not able to discover the types inside this folder, despite the fact we're using a TS version greater than 3.1.

This will likely effect other types which utilise versioned types in a similar fashion.

### Desired behavior:

This should not error.

### Test code to reproduce

https://github.com/OliverJAsh/cypress-sinon-types-test

Run `yarn` and then `tsc`.

### Versions

Latest Cypress
macOS

**Comment by jennifer-shehane** [comment]
This still fails in 4.5.0, so doesn't look like a regression from https://github.com/cypress-io/cypress/pull/7352 exactly.

**Comment by OliverJAsh** [comment]
Huh, it definitely worked for us on 4.4 until we upgraded. I can look again

**Comment by OliverJAsh** [comment]
Here's a reduced test case to show this was working in 4.4.0: https://github.com/OliverJAsh/cypress-sinon-types-test

**Comment by jennifer-shehane** [comment]
Ok, yes, I see a bunch of errors in 4.5.0, one being 

```
index.ts:3:29 - error TS2344: Type 'number' does not satisfy the constraint 'any[]'.

3 type F = sinon.SinonSpyCall<number, string>;
```

In 4.6.0, there is only 1 error thrown which is 

```
index.ts:3:10 - error TS2315: Type 'SinonSpyCall' is not generic.

3 type F = sinon.SinonSpyCall<number, string>;
```

So, yes this appears to have been introduced in 4.6.0. Maybe due to the commit linked to above.

**Comment by OliverJAsh** [comment]
> I see a bunch of errors in 4.5.0

Apologoies, this is because I gave a bad example. It should be using `number[]`.

**Comment by sainthkh** [comment]
Unfortunately, it's impossible to fix with current technology. Many types are directly copied from node_modules and referenced to Cypress to avoid the conflict with the Jest types.
