### ISSUE TITLE
TypeError Array(...).keys(...).slice is not a function after upgrade from 3.8.3 to 4.4.1

### ISSUE THREAD

**Issue by Kimserey** [cypress-io/cypress#7098]
### Current behavior:

I am using Cypress on an Angular application.

The following test is working on version 3.8.3

```js
it('cy.get() - query DOM elements', () => {
  let x = [...Array(100).keys()].map(x => x + "");
  cy.server().route('/test', x);
  cy.get('[data-cy=landmark]').invoke('text').should('contain', 'Welcome');
})
```

**but throws an error on 4.4.1**

```
TypeError: Array(...).keys(...).slice is not a function
    at Context.<anonymous> (http://localhost:4200/__cypress/tests?p=cypress/integration/examples/querying.spec.js-628:8:35)
```

### Test code to reproduce

Repository demonstrating the problem: https://github.com/Kimserey/cypress-test-issue
- branch `master` is 3.8.3
- branch `upgrade-4` is 4.4.1

1. From the root directory, run `ng serve`,
2. From the root directory, start cypress `npx cypress open`,
3. The only test in the integration specs will throw the TypeError.

## Versions

Cypress 4.4.1

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this solely from the snippet provided. 

<img width="661" alt="Screen Shot 2020-04-22 at 1 42 41 PM" src="https://user-images.githubusercontent.com/1271364/79951736-41fd3080-849f-11ea-8120-9022ab64fa7a.png">

I am able to reproduce this from the repository provided, so this means it is something related to the environment setup. I suspect that it has something to do with the TypeScript configuration, since this begins failing in 4.4.0, which introduced out of the box TypeScript support in https://github.com/cypress-io/cypress/pull/5906

Indeed, I've confirmed that the test code above does not work when there is a `devDependency` of `typescript`. cc @sainthkh 

## To Reproduce

`spec.js`

```js
let x = [...Array(100).keys()].map(x => x + "");
```

`package.json`

```json
{
  "name": "cypress-test",
  "scripts": {},
  "devDependencies": {
    "cypress": "4.4.1",
    "typescript": "3.8.3"
  }
}
```

### 4.4.0

![Screen Shot 2020-04-22 at 1 54 34 PM](https://user-images.githubusercontent.com/1271364/79952786-f64b8680-84a0-11ea-90bc-de6d8a729032.png)


### 4.4.1

<img width="483" alt="Screen Shot 2020-04-22 at 1 59 23 PM" src="https://user-images.githubusercontent.com/1271364/79953188-7f62bd80-84a1-11ea-9823-9b02740de197.png">

### TypeScript version 3.5.3

<img width="490" alt="Screen Shot 2020-04-22 at 2 20 20 PM" src="https://user-images.githubusercontent.com/1271364/79955180-6ad3f480-84a4-11ea-8ea2-3230163fa67a.png">


### TypeScript version 3.8.3 (current)

<img width="484" alt="Screen Shot 2020-04-22 at 2 19 41 PM" src="https://user-images.githubusercontent.com/1271364/79955119-54c63400-84a4-11ea-9905-426f687d0821.png">



## Workaround

Downgrade to Cypress 4.3.0 for now.

**Comment by sainthkh** [comment]
It happened because I didn't set up [`downlevelIteration` option](https://www.typescriptlang.org/v2/en/tsconfig#downlevelIteration). It will be fixed in the preprocessor first and added to Cypress.
