### PR TITLE
fix: add yarn v2 pnp support to default webpack processor

### LINKED ISSUE #8008: Cypress and Yarn 2 PNP support
### Current behavior:

In Yarn 2 monorepo I have a package `a` and tests in package `b`.

When I do

```js
// b/cypress/plugins/index
module.exports = require('a/src/cypress/plugins');
```

It works as expected.

But

```js
// a/cypress/commands/index
require('a/src/cypress/commands');
```

Fails with error:

```
Oops...we found an error preparing this test file:

  /Users/xxx/b/cypress/support/index.js

The error was:

Error: Cannot find module 'a/src/cypress/support' from '/Users/xxx/b/cypress/support'
```

Looks like Yarn's Plug'n'play file `.pnp.js` is not present in second (commands) context.

### Desired behavior:

Require of monorepo packages should work.

### LINKED ISSUE #16111: Plugins file fails on lodash import after upgrade to 7.1.0
### Current behavior
When I upgrade my cypress instance from `6.8.0` to `7.1.0` I get an error where cypress thinks that my plugins file has invalid syntax, but the root cause is that it can't import `lodash` that I use for deep merge of default & our settings.

This used to work fine & I've tried to mitigate this by creating a custom importer akin to this: https://stackoverflow.com/questions/62298396/making-a-dependencys-dependencies-available-with-yarn-2/64242991#64242991 …alas it didn't help

I do have `lodash` installed in the root "workspace".

```
**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `…/web-ui/cypress/plugins/index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** Error: Cannot find module 'lodash'
Require stack:
- …/web-ui/cypress/plugins/index.ts
- /home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
- /home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/dev/…/pool/web-ui/cypress/plugins/index.ts:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at runPlugins (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:175:15)
    at Object.<anonymous> (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

**Stack trace:**
```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `…/web-ui/cypress/plugins/index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/errors.js:988:15)
    at EventEmitter.<anonymous> (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/index.js:154:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Test code to reproduce
I've tried to reproduce this in the `cypress-test-tiny`, but wasn't able to… if you can point me in some direction I'll provide what's needed

### Versions
- Operating System: Ubuntu 20.10
- Cypress: 7.1.0
- Yarn: 2.4.0-git.20210226.hash-97663a9d with P'n'P enabled & workspaces setup
- Typescript: 4.2.3

### PR DESCRIPTION
**Pull request by missing1984**
- Close #16111
- Close #8008 

### User facing changelog

Add Yarn v2 pnp support to our default webpack processor.

### Additional details
This MR addressed couple issues around yarn v2 pnp support.
- Fix typescript detection. Basically ported https://github.com/cypress-io/cypress/pull/15623 over
- Fix #16111, bring back NODE_OPTIONS env variable in plugin child process so yarn can pick up pnp runtime
- Add pnp-webpack-plugin to `@cypress/webpack-batteries-included-preprocessor` so we can support pnp out of the box. #8008
- Add unit and e2e test case

### How has the user experience changed?
Once this merged, Yarn v2 pnp should work with Cypress out of the box

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by missing1984** [comment]
hmm, looks like the failing CI is caused by network issue?
```
yarn run v1.22.10
$ node ../../scripts/run-ct-examples.js --examplesList=./examples.env
Running tests in /root/cypress/npm/vue
Running yarn install in project /root/cypress/npm/vue
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```
Can someone help to retry the job?

**Comment by missing1984** [comment]
@jennifer-shehane @flotwig since you're marked as reviewers.... anything else i can do to get this merge?

**Comment by flotwig** [comment]
> @jennifer-shehane @flotwig since you're marked as reviewers.... anything else i can do to get this merge?

Nothing right now. We are working on getting 8.0 out the door right now, but this is a priority for me to get reviewed after 8.0 is out.

**Comment by kubijo** [comment]
Is there anything I can do locally to make the pnp API work until this gets released? Id like to try 8.0, but this blocks me

**Review by flotwig — APPROVED** [review]
> There're 2 ways to make Cypress support yarn v2 natively (and close #8008)
> 
>     1. Switch to use webpack5 from default webpack preprocessor which has built-in pnp support.
> 
>     2. Add `pnp-webpack-plugin` to our `@cypress/webpack-batteries-included-preprocessor` once [Fix #32 try to use findPnpApi to locate pnpapi arcanis/pnp-webpack-plugin#37](https://github.com/arcanis/pnp-webpack-plugin/pull/37)
> 
> 
> I can follow up on option 2

Upgrading the preprocessor to Webpack 5 would be a better solution long-term, but it would have to wait until Cypress 9 since it would be a breaking change. If you want to proceed with #2, that would be a good change to pull in for now that would be non-breaking.

Other than that, tested manually with a local yarn v2 project and `yarn node` now seems to properly set up `NODE_OPTIONS` for the plugins process again.

**Comment by missing1984** [comment]
Thanks. ping @arcanis any chance we can get https://github.com/arcanis/pnp-webpack-plugin/pull/37 merged?

**Comment by missing1984** [comment]
Thanks @arcanis, https://github.com/arcanis/pnp-webpack-plugin/pull/37 is merged and i am going to add it to our default webpack profile so we can support pnp natively.

**Comment by missing1984** [comment]
@flotwig @jennifer-shehane I've added pnp-webpack-plugin to our `@cypress/webpack-batteries-included-preprocessor` so we can support pnp natively and close #8008. MR title and description are updated as well.

Let me know if there's anything i should do.

**Review by flotwig — APPROVED** [review]
Looks good to me, @chrisbreiding can you take a quick look now that this is going to modify the behavior of the webpack preprocessor?

**Review by chrisbreiding — APPROVED** [review]

**Comment by flotwig** [comment]
@missing1984 Thank you for the contribution!
