### ISSUE TITLE
Cypress crash with plugins 'aSourceMapConsumer.eachMapping is not a function' error

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#14587]
### Current behavior

The Test Runner errors when attempting to run and throws the error below from plugins. 

This happens in Cypress 5.4.0+, introduced in https://github.com/cypress-io/cypress/pull/8826. Downgrading to 5.3.0 resolves the issue.

```
TypeError: aSourceMapConsumer.eachMapping is not a function
    at Function.fromStringWithSourceMap (/Users/jennifer/Dev/preprocessor-crash/node_modules/source-map/lib/source-node.js:87:24)
    at SourceMapSource.node (/Users/jennifer/Dev/preprocessor-crash/node_modules/webpack-sources/lib/SourceMapSource.js:32:25)
    at ReplaceSource.node (/Users/jennifer/Dev/preprocessor-crash/node_modules/webpack-sources/lib/ReplaceSource.js:82:27)
    at CachedSource.node (/Users/jennifer/Dev/preprocessor-crash/node_modules/webpack-sources/lib/CachedSource.js:18:24)
    at /Users/jennifer/Dev/preprocessor-crash/node_modules/webpack-sources/lib/ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (/Users/jennifer/Dev/preprocessor-crash/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (/Users/jennifer/Dev/preprocessor-crash/node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
    at CachedSource.sourceAndMap (/Users/jennifer/Dev/preprocessor-crash/node_modules/webpack-sources/lib/CachedSource.js:58:31)
    at getTaskForFile (/Users/jennifer/Dev/preprocessor-crash/node_modules/webpack/lib/SourceMapDevToolPlugin.js:64:30)
    at /Users/jennifer/Dev/preprocessor-crash/node_modules/webpack/lib/SourceMapDevToolPlugin.js:206:20
    at Array.forEach (<anonymous>)
    at /Users/jennifer/Dev/preprocessor-crash/node_modules/webpack/lib/SourceMapDevToolPlugin.js:177:12
    at SyncHook.eval (eval at create (/Users/jennifer/Dev/preprocessor-crash/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/jennifer/Dev/preprocessor-crash/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/jennifer/Dev/preprocessor-crash/node_modules/webpack/lib/Compilation.js:1413:42
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jennifer/Dev/preprocessor-crash/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jennifer/Dev/preprocessor-crash/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/jennifer/Dev/preprocessor-crash/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jennifer/Dev/preprocessor-crash/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jennifer/Dev/preprocessor-crash/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/jennifer/Dev/preprocessor-crash/node_modules/webpack/lib/Compilation.js:1405:32
```

<img width="802" alt="Screen Shot 2021-01-15 at 2 56 45 PM" src="https://user-images.githubusercontent.com/1271364/104699986-ea47d900-5741-11eb-9bfa-caa90c6f5abc.png">

### Test code to reproduce

**Repo to reproduce:** https://github.com/jennifer-shehane/preprocessor-crash

Basic code to reproduce:

`package.json`

```json
{
  "dependencies": {
    "@apollo/client": "3.2.0"
  },
  "devDependencies": {
    "cypress": "6.2.1",
    "typescript": "4.1.3"
  }
}
```

`tsconfig.json`

```json
{
  "compilerOptions": {
    "baseUrl": "node_modules",
  }
}
```

- `npm i` and `cypress run` or open to see error

### Versions

Cypress 5.4.0+

**Comment by chrisbreiding** [comment]
The reason this is happening is that webpack uses [`webpack-sources`](https://github.com/webpack/webpack-sources) for source mapping and it in turn uses [`source-map`](https://github.com/mozilla/source-map). `webpack-sources` needs `source-map` to be version 0.6.x or lower because in 0.7.0, `source-map` made everything asynchronous so [this call](https://github.com/webpack/webpack-sources/blob/master/lib/SourceMapSource.js#L193) no longer works because `new SourceMapConsumer()` returns a promise in 0.7.0+ instead of a `SourceMapConsumer` instance. 

This normally would be fine because `webpack-source` would use the version of `source-map` that it specifies. However, in this case, setting `"baseUrl": "node_modules"` in `tscsonfig.json` messes with the node package resolution and causes `webpack-sources` to load the version of `source-map` that `@apollo/client` brings along, which is 0.7.3.

There are 2 possible solutions to this:

- Remove `"baseUrl": "node_modules"` from `tsconfig.json`. I think we used to recommend this in [our TypeScript doc](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json), but we no longer do. If there's some issue that's solved by setting it, I'd prefer to tackle that in a different way. As it is, this example is a bit contrived because users shouldn't be setting the baseUrl to `node_modules`.
- Alternatively, if `"baseUrl": "node_modules"` is necessary, it can be solved by installing `source-map@0.6.1` directly. That way `webpack-soruces` finds the version it needs. 
	```bash
	npm install --save-dev source-map@0.6.1
	```

**Comment by lgenzelis** [comment]
Leaving my 5 cents here. I was using `baseUrl` because I want to have `paths` (we alias "root" to "~/"). We could set 
```json
"baseUrl": "./",
"paths": { "~/*": ["*"] }
```
But with that something from `<rootDir>/utils/file.ts` could be imported as either `~/utils/file.ts` or as `utils/file.ts`. We want to allow the former but definitely not the latter, since it makes code less readable ("is this `import` a local module or something from node_modules?"). Next best thing: setting `"baseUrl": "node_modules"` and `"paths": { "~/*": ["../*"] }`. But since that causes this bug with cypress, now we just have 
```json
"baseUrl": "dir_that_does_not_exist",
"paths": {
  "~/*": ["../*"]
}
```
This doesn't have any issues with `cypress` and keeps our aliases working as always.
