### ISSUE TITLE
Cypress 5.x does not support UMD module type in tsconfig.json

### ISSUE THREAD

**Issue by kpittman-securus** [cypress-io/cypress#8587]
### Current behavior:
When I upgrade from v4.12.1 to v5.x I get an error like this:

```
The following error originated from your test code, not from Cypress.

  > Cannot find module '../../path/to/something/that/used/to/work'

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
src/integration/nameOfSpec%20sync:2:1
  1 | function webpackEmptyContext(req) {
> 2 | 	var e = new Error("Cannot find module '" + req + "'");
    | ^
  3 | 	e.code = 'MODULE_NOT_FOUND';
  4 | 	throw e;
  5 | }
```

### Workaround
Change tsconfig.json from `"module": "umd"` to `"module": "commonjs"`. Our project had this set to `umd` for the past 2 years for whatever reason, made sense back at the time to have it that way. Thankfully, setting it to `commonjs` does not appear to break anything with our tests so the workaround is acceptable for us.

I did not find anything in the Cypress docs when googling about "cypress tsconfig module umd" so it seems like this is undocumented.

### Desired behavior:
It would work without throwing an error about "Cannot find module".

Or: It should be documented/warned that module type must NOT be `umd` (required to be `commonjs`? I have not tried other options other than `commonjs` and `umd`) - possibly could be documented [here](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json)

### Test code to reproduce
In project's `tsconfig.json` set `"module": "umd"` and you will receive an error during test execution. 

Repro steps:

* clone https://github.com/cypress-io/cypress-and-jest-typescript-example
* Bump cypress version to 5.x
* Set tsconfig.json to have `"module": "umd"`
* Run `npm run cy:open` and run the spec
* error is shown:

```
An uncaught error was detected outside of a testfailed
No commands were issued in this test.
Error
The following error originated from your test code, not from Cypress.

  > Cannot find module '../../src/foo'

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
cypress/integration%20sync:2:1
  1 | function webpackEmptyContext(req) {
> 2 | 	var e = new Error("Cannot find module '" + req + "'");
    | ^
  3 | 	e.code = 'MODULE_NOT_FOUND';
  4 | 	throw e;
  5 | }
```

The workaround is just not to use the `umd` module type, but it would be good if cypress could either warn against this during runtime or at least here: https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json

And maybe someone has a legit use case for using `umd`

* but I don't know what that would be.

### Versions
Cypress v5.0.0, 5.1.0, 5.2.0

**Comment by bahmutov** [comment]
I have reproduced it (and bumped cypress dependency in the project to v5), when changing the module `umd` does fail badly. Probably need to enforce it, which is weird, I thought we did it (but we probably change it from es6 to commonjs, but not for umd)

**Comment by BlueWinds** [comment]
Going to close this after a couple years of inactivity and the release of 6 major Cypress versions. If you're still running into problems with a more recent release, please feel free to open a new issue and we'll try to be better about looking at things.
