### PR TITLE
fix: wrap the `tsx` loader path in quotes

### LINKED ISSUE #32398: Error when running "cypress open"
### Current behavior

When I run "cypress open", I expect the cypress app to open, but it fails and throws an error as shown in the following figure.

Image

### Debug logs

```Text
PS F:\cypress project> npm run cy:open

> cy:open
> cypress open



DevTools listening on ws://127.0.0.1:63073/devtools/browser/cb954276-77c6-4669-b02e-b94c42dc9d03
<<<CYPRESS.STDERR.START>>>node:internal/modules/esm/resolve:265
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\IT' imported from F:\cypress project\
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:322:34)
    at loadESM (node:internal/process/esm_loader:23:33)
    at runMainESM (node:internal/modules/run_main:98:21)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:131:5) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Users/IT'
}

Node.js v20.12.2
<<<CYPRESS.STDERR.END>>>
```

### Cypress Version

15.0.0

### Node version

20.12.2

### Package Manager

npm

### Package Manager Version

10.8.0

### Operating system

Windows

### Operating System Version

10

### Other

Cypress v14.2.0 works fine with me.

My windows account user name is "IT SHOP", which makes the issue, as Cypress is trying to get something from a path containing "IT SHOP", but it fails to read it as "IT SHOP", it fails to read the space in the middle and just read "IT".

One solution is to change my user name, but my user name works fine on Cypress v14.2.0 and shouldn't be an issue, so this issue has been introduced in a newer version.

Maybe Cypress concatenates the account user name into a path to use it in the terminal without putting the whole path into string quotes.

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #32398

### Additional details

Multiple issues on Windows have reported that there are issues running Cypress 15 when running on Windows with spaces in their project path. To fix this, we need to wrap the `tsx` loader path in quotes so the loader can be fully resolved.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@AtofStryker Is it possible to add a failing test for this?

**Comment by AtofStryker** [comment]
> @AtofStryker Is it possible to add a failing test for this?

@jennifer-shehane instead we are changing the regular expression to check for quotes present in the path so a regression test is present if the source code changes

**Review by jennifer-shehane — APPROVED** [review]
@AtofStryker I missed that change being in the spec file! Should be fine if the windows tests pass.

**Comment by AtofStryker** [comment]
verified fix with built binary 
image
