### ISSUE TITLE
Webpack error after upgrade to 11.0

### ISSUE THREAD

**Issue by shunyun-bp** [cypress-io/cypress#24625]
### Current behavior

After installing Cypress version 11.0.0 all tests fail with the same error:
`Error: Webpack Compilation Error
./cypress/e2e/home_page.cy.js
Module build failed (from /Users/seanonion/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/lib/cross-origin-callback-loader.js):
Error: Cannot find module '/Users/seanonion/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/parser/lib/index.js'. Please verify that the package.json has a valid "main" entry`

[Cypress 11 error.log](https://github.com/cypress-io/cypress/files/9974105/Cypress.11.error.log)

### Desired behavior

Run tests that were successfully running in previous version (v10.11.0). 

### Test code to reproduce

cannot reproduce into a public repo

### Cypress Version

11.0.0

### Node version

v16.13.2

### Operating System

macOS 12.6

### Other

I had done nothing to setup webpack-preprocessor in 10.11.0 and earlier, so no idea why this is happening now.

**Comment by shunyun-bp** [comment]
[cypress 11 debug.txt](https://github.com/cypress-io/cypress/files/9974578/cypress.11.debug.txt)

**Comment by chris-mclennan** [comment]
I too am getting the same error message

**Comment by bennymeade** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/24611

**Comment by ryanthemanuel** [comment]
This is a duplicate of #24611 and will be fixed with https://github.com/cypress-io/cypress/pull/24630
