### ISSUE TITLE
onError is not a function

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#7217]
### Current behavior:

Test runner can fail with the following error (first seen [here](https://github.com/cypress-io/cypress/issues/3310#issuecomment-612101639))

```
onError is not a function
```

![](https://user-images.githubusercontent.com/28731357/79005194-a0004e80-7b56-11ea-8522-d4f98a680b0c.png)

This was introduced in https://github.com/cypress-io/cypress/pull/6610

### Desired behavior:

This shouldn't happen, instead `onError` should be defined and enable proper error handling to occur. As it is, the true error is obscured.

### Test code to reproduce

Can be simulated by stopping the browser from connecting by messing with the root html that `packages/runner` serves.

### Versions

Cypress 4.2.0+
