### ISSUE TITLE
After screenshot app under test is incorrectly positioned

### ISSUE THREAD

**Issue by rowanhill** [cypress-io/cypress#7466]
### Current behavior:

I'm finding that after taking a screenshot (either with cy.screenshot() or on a particular element), the 'app under test' iframe is incorrectly repositioned: it is offset too far to the right, leaving part of the iframe obscured. See the screenshot below

<img width="1312" alt="Cypress 4.6.0 after a screenshot has been taken, with the AUT iframe too far to the right" src="https://user-images.githubusercontent.com/2607287/82727221-1b6e2780-9ce1-11ea-89ee-23bbdc2cf633.png">

### Desired behavior:

I would expect that, after positioning for a screenshot, the app under test is repositioned where it originally was, flush with the reporter, and aligned with the runner header.

### Test code to reproduce:

I'm able to reproduce it with the following test:

```javascript
describe('taking a screenshot', () => {
  it('repositions the app under test iframe incorrectly', () => {
      cy.visit('https://example.cypress.io')
      cy.screenshot();
  });
});
```

Sorry for not forking cypress-test-tiny - I tried, but had troubles getting cypress to run there (I get `TypeError: ts.transpileModule is not a function` errors, which I assume are entirely unrelated so I haven't investigated further).

### Versions

- Cypress 4.6.0 (I know 3.8.1 did _not_ have this issue)
- Chrome 81 & Electron 80
- macOS Catalina 10.15.4

**Comment by rowanhill** [comment]
FYI, it looks to me like it's an issue with [this](https://github.com/cypress-io/cypress/blame/14c84496f18e351146252f80c7cde8c0ac503aae/packages/runner/src/app/app.jsx#L140) line and [this](https://github.com/cypress-io/cypress/blame/14c84496f18e351146252f80c7cde8c0ac503aae/packages/runner/src/app/app.jsx#L179) line - the iframe's left is being set the the container's left after screenshot.

I would think the two node's lefts ought to be tracked (and restored) separately. I've made that change ([here](https://github.com/rowanhill/cypress/commit/02d0d6cc30d6b3658495e9e26f7574a833c88d5e)), and it resolves my issue locally, at least.

I haven't raised a PR as I'd need a bit of guidance on writing tests for this first - the current <App /> unit tests only use shallow() rendering (and skip lifecyle methods), so aren't suitable; it looks like it would be a pain to test by mount()ing <App /> (because there's a lot of mocking to be done); and I'm not quite sure how to navigate the e2e tests (and running them seems to take a *long* time).

**Comment by jennifer-shehane** [comment]
Yeah, this was introduced in #7203 and will be fixed as part of #7448. 

### 4.5.0

<img width="1679" alt="Screen Shot 2020-05-26 at 1 50 04 PM" src="https://user-images.githubusercontent.com/1271364/82871581-d4d63280-9f57-11ea-9483-3b790b96cbb1.png">


### 4.6.0

<img width="1678" alt="Screen Shot 2020-05-26 at 1 47 54 PM" src="https://user-images.githubusercontent.com/1271364/82871443-96d90e80-9f57-11ea-878a-76135b4f52a5.png">


### Workaround

Downgrade to 4.5.0
