### PR TITLE
Fix 'onError is not function' bug

### LINKED ISSUE #7217: onError is not a function
### Current behavior:

Test runner can fail with the following error (first seen [here](https://github.com/cypress-io/cypress/issues/3310#issuecomment-612101639))

```
onError is not a function
```

This was introduced in https://github.com/cypress-io/cypress/pull/6610

### Desired behavior:

This shouldn't happen, instead `onError` should be defined and enable proper error handling to occur. As it is, the true error is obscured.

### Test code to reproduce

Can be simulated by stopping the browser from connecting by messing with the root html that `packages/runner` serves.

### Versions

Cypress 4.2.0+

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #7217 

### User facing changelog

- Fixed a bug where when a browser can't connect, Cypress displays `onError is not a function`

### Additional details

A bug in Cypress's error handling caused an internal error to show when the browser couldn't connect. It didn't necessarily obscure the original error, as we don't display a specific error from the browser not connecting, but it was confusing.

### How has the user experience changed?

If the browser can't connect, the Cypress process will still fail, but it will no longer show the error `onError is not a function`.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/test/e2e/3_plugins_spec.js [hunk 1]
```diff
@@ -29,17 +29,15 @@ describe('e2e plugins', function () {
...
-  // better to skip this for now so it doesn't hang up other work
-  it.skip('fails when there is an async error at the root', function () {
-    return e2e.exec(this, {
-      spec: 'app_spec.js',
-      project: pluginsRootAsyncError,
-      sanitizeScreenshotDimensions: true,
-      snapshot: true,
-      expectedExitCode: 1,
-    })
+  e2e.it('fails when there is an async error at the root', {
```
Comment (chrisbreiding) [inline packages/server/test/e2e/3_plugins_spec.js:32]: This is a related test that was skipped before because it was flaky. I think I have it more reliable now.

File: packages/server/test/e2e/3_issue_7217_spec.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
+const path = require('path')
+const e2e = require('../support/helpers/e2e')
+
+describe('e2e issue 7217', () => {
+  e2e.setup()
+
+  // this test ensures that the right error is reported if the
+  // browser can't connect
+  // https://github.com/cypress-io/cypress/issues/7217
+  e2e.it('shows correct error if browser does not connect', {
```
Comment (chrisbreiding) [inline packages/server/test/e2e/3_issue_7217_spec.ts:10]: Before the fix, this would cause the `onError is not a function` issue.

File: packages/server/lib/modes/run.js [hunk 3]
```diff
@@ -995,7 +995,7 @@ module.exports = {
 
   waitForBrowserToConnect (options = {}) {
     const { project, socketId, timeout, onError } = options
-
+    const browserTimeout = process.env.CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT || timeout || 60000
```
Comment (chrisbreiding) [inline packages/server/lib/modes/run.js:998]: Allows shortening the timeout so the e2e test takes less time to fail.

File: packages/server/lib/controllers/runner.coffee [hunk 4]
```diff
@@ -43,7 +43,9 @@ module.exports = {
     ## https://github.com/cypress-io/cypress/issues/4952
     base64Config = Buffer.from(JSON.stringify(config)).toString('base64')
 
-    res.render(runner.getPathToIndex(), {
+    runnerPath = process.env.CYPRESS_INTERNAL_RUNNER_PATH or runner.getPathToIndex()
```
Comment (chrisbreiding) [inline packages/server/lib/controllers/runner.coffee:46]: Simplest way I could figure out to simulate a browser that won't connect is rendering an html page that doesn't have `socket.io`.
