### ISSUE TITLE
Webpack error after Cypress 11.0.0 upgrade

### ISSUE THREAD

**Issue by jvavre** [cypress-io/cypress#24633]
### Current behavior

Node: v16.14.2
NPM: 8.5.0

No component testing in the automation suite, running with no issues on 10.11.0

Dependencies (package.json):

```
  {
  "dependencies": {
    "axios": "0.24.0",
    "faker": "4.1.0",
    "lodash": "4.17.21",
    "moment": "2.24.0",
    "nconf": "0.10.0",
    "node-emoji": "1.8.1"
  },
  "devDependencies": {
    "@babel/core": "7.11.5",
    "@babel/node": "7.10.5",
    "@babel/plugin-transform-runtime": "7.11.5",
    "@babel/preset-env": "7.11.5",
    "cypress": "11.0.0",
    "cypress-testrail-accumulative-reporter": "1.1.4",
    "eslint": "6.0.1",
    "eslint-config-prettier": "3.1.0",
    "eslint-plugin-cypress": "2.2.1",
    "eslint-plugin-prettier": "3.1.0",
    "eslint-plugin-react": "7.20.6",
    "fs-extra": "7.0.1",
    "prettier": "2.1.1"
  }```

Getting an error when trying to run any of test .cy files in headed mode, both in Electron & Chrome - see below

### Desired behavior

Spec file is executed with no issues

### Test code to reproduce

Upgraded to latest Cypress, getting error below:

```Error: Webpack Compilation Error
/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/objectSpread.js
Module not found: Error: Can't resolve './defineProperty.js' in '/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers'
Looked for and couldn't find the file at the following paths:
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.js]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.json]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.jsx]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.mjs]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.coffee]
 @ /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/objectSpread.js 1:21-51
 @ ./cypress/support/commands/event.js
 @ ./cypress/support/e2e.js
 
    at Watching.handle [as handler] (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:230:23)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:98:28)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:54:20
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23)```

### Cypress Version

11.0.0

### Node version

v16.14.2

### Operating System

macOS Monteray 12.5.1

### Debug Logs

```shell
Upgraded to latest Cypress, getting error below (same as above):

: Webpack Compilation Error
/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/objectSpread.js
Module not found: Error: Can't resolve './defineProperty.js' in '/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers'
Looked for and couldn't find the file at the following paths:
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.js]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.json]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.jsx]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.mjs]
[/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/defineProperty.js.coffee]
 @ /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/objectSpread.js 1:21-51
 @ ./cypress/support/commands/event.js
 @ ./cypress/support/e2e.js
 
    at Watching.handle [as handler] (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:230:23)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:98:28)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:54:20
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/m1_mac_pro_user/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23)
```

### Other

Please, let me know if I should provide any more details, this is my first reported issue. Thanks!

**Comment by ryanthemanuel** [comment]
This was fixed with this PR: https://github.com/cypress-io/cypress/pull/24630 and will be released on 11.0.1

**Comment by fappaz** [comment]
I'm having the same issue after updating Cypress v10 to v11 on a Windows 10 PC. It also happens in headless mode.

```
Error: Webpack Compilation Error
C:/Users/Dev/AppData/Local/Cypress/Cache/11.0.0/Cypress/resources/app/node_modules/@babel/runtime/helpers/objectSpread.js
Module not found: Error: Can't resolve './defineProperty.js' in 'C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@babel\runtime\helpers'
Looked for and couldn't find the file at the following paths:
[C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@babel\runtime\helpers\defineProperty.js]
[C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@babel\runtime\helpers\defineProperty.js.js]
[C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@babel\runtime\helpers\defineProperty.js.json]
[C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@babel\runtime\helpers\defineProperty.js.jsx]
[C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@babel\runtime\helpers\defineProperty.js.mjs]
[C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@babel\runtime\helpers\defineProperty.js.coffee]
 @ C:/Users/Dev/AppData/Local/Cypress/Cache/11.0.0/Cypress/resources/app/node_modules/@babel/runtime/helpers/objectSpread.js 1:21-51
 @ ./cypress/e2e/workflows/deviceId/walkInPatientDeviceId.cy.js
 
    at Watching.handle [as handler] (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-preprocessor\dist\index.js:230:23)
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:98:28)
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:73:19
    at Compiler.emitRecords (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:54:20
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:482:27
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:464:33
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Users\Dev\AppData\Local\Cypress\Cache\11.0.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23)
```

**Comment by ryanthemanuel** [comment]
@fappaz I see from your error logs that you are using 11.0.0. Have you tried updating to 11.0.1? This should have been resolved in 11.0.1

**Comment by ryanthemanuel** [comment]
@fappaz, we have a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
