### ISSUE TITLE
Webpack compilation error on version 5.4

### ISSUE THREAD

**Issue by vrknetha** [cypress-io/cypress#8853]
![image](https://user-images.githubusercontent.com/20596261/96091455-3f781280-0ee7-11eb-8563-dc8b18af9c6e.png)

All works fine with 5.3 but when upgraded to 5.4, this error comes up

```js
const {generateEmail, getOTPFromEmail} = require('../../playwright/utils/testUtilities');
const {ConvosightLoginWithGroups, ConvosightLoginNoGroups} = require('./../cookie-extractor/scripts');
const {deleteUser, getUserOtp, deleteCampaign} = require('../../playwright/utils/database.adapter');
const {cypressBrowserPermissionsPlugin} = require('cypress-browser-permissions');
const xlsx = require('node-xlsx').default;
const fs = require('fs');
const path = require('path');
module.exports = (on, config) => {
	// `on` is used to hook into various events Cypress emits
	// `config` is the resolved Cypress config
	require('@cypress/code-coverage/task')(on, config);
	config = cypressBrowserPermissionsPlugin(on, config);
	on('task', {
		ConvosightLoginWithGroups({user, pass}) {
			return new Promise(async resolve => {
				resolve(await ConvosightLoginWithGroups(user, pass));
			});
		},

		ConvosightLoginNoGroups({user, pass}) {
			return new Promise(async resolve => {
				resolve(await ConvosightLoginNoGroups(user, pass));
			});
		},

		getOTPFromEmail({email}) {
			return new Promise(async resolve => {
				resolve(await getOTPFromEmail(email));
			});
		},

		failed: require('cypress-failed-log/src/failed')(),

		DeleteUserFromDatabase({userEmail}) {
			return deleteUser(userEmail);
		},

		GetOtpFromDatabase({userEmail}) {
			return getUserOtp(userEmail);
		},

		generateEmail() {
			return generateEmail();
		},

		DeleteCampaign({campaignName}) {
			return new Promise(async resolve => {
				resolve(await deleteCampaign(campaignName));
			});
		},

		parseXlsx({filePath}) {
			return new Promise((resolve, reject) => {
				try {
					const jsonData = xlsx.parse(fs.readFileSync(filePath));
					resolve(jsonData);
				} catch (e) {
					reject(e);
				}
			});
		}
	});

	on('before:browser:launch', (browser = {}, launchOptions) => {
		const downloadDirectory = path.join(__dirname, '..', 'excelDownloads');
		launchOptions.preferences.default['download'] = {default_directory: downloadDirectory};
		return launchOptions;
	});

	return config;
};

```

**Comment by jennifer-shehane** [comment]
I can't recreate the error from the information provided. Please provide a repository that we can fully run without any other dependencies that recreates the issue. Likely there's something else in your project files that causes this error. Please provide that so we can work on fixing this.

**Comment by surajvbhattathiri** [comment]
I have also run into the same issue. I was trying to learn how to use cypress with istanbuljs for angular code coverage.
Please refer to https://github.com/surajvbhattathiri/cypress540-webpackissue

There is only one single spec file 'sample1.spec.js' and with 5.4.0 it throws webpack compilation error

This works fine with 5.3.0

**Comment by mdunicorn** [comment]
This is the same issue as #8864

**Comment by vrknetha** [comment]
I have fixed it my moving the browser list to package.json. Already it is not a perfect fix but a work around.

**Comment by jennifer-shehane** [comment]
Duplicate of #8864
