### ISSUE TITLE
Adding custom commands with typescript definitions leads to error

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1065]
```js
Cypress.Commands.add('myCustomCommand', '...')
````

Using TypeScript now results in... 

`Property ‘myCustomCommand’ does not exist on type ‘Chainable’)`

How do we fix this @NicholasBoll  @bahmutov

**Comment by bahmutov** [comment]
Good concrete example where we could use it today is https://github.com/cypress-io/snapshot

User adds custom command (in `cypress/support/commands.js`
```
require('@cypress/snapshot')()
```
and now has commanf
```
cy.wrap(42).snapshot()
// or
cy.wrap(42).snapshot({name: 'meaning of life'})
```
It would be nice to add this command to the `cy` type after https://github.com/cypress-io/snapshot/blob/master/src/index.js#L155

```
Cypress.Commands.add('snapshot', { prevSubject: true }, snapshot)
```

**Comment by shcallaway** [comment]
One way to do this would be to export the `Cypress` namespace and allow TypeScript users to extend the `Chainable` interface.

**Comment by NicholasBoll** [comment]
@shcallaway is exactly right. Chainable interfaces have to be extended:

```ts
declare namespace Cypress {
  interface Chainable<Subject> {
    snapshow(value: { name: string }): Chainable<Subject>
  }
}

Cypress.Commands.add('snapshot', { prevSubject: true}, snapshot)
```

**Comment by brian-mann** [comment]
So we don't have to make any changes on our end right? We just need to update the Typescript recipes to show this... @bahmutov  ?

**Comment by NicholasBoll** [comment]
I was looking at the examples `preprocessors__typescript-webpack` and `preprocessors__typescript-browserify`. TypeScript will not allow you to extend a namespace if the file is a `module` (has import/export/require). To get around this in the example, the `command.ts` file(s) cannot import/export anything. They simple contain the following code:

`commands.ts`:
```ts
declare namespace Cypress {
  interface Chainable<Subject> {
    myCustomCommand: typeof myCustomCommand
  }
}

function myCustomCommand(value: string): Cypress.Chainable<JQuery> {
  return cy.get('foo')
}

Cypress.Commands.add('myCustomCommand', myCustomCommand)

cy.get('foo').myCustomCommand('foo')
```

And the index.ts simply imports it: `import './command'`. I'll also note the `tsconfig.json` needs to include all files in support for this to work (it looks like it does).

**Comment by shcallaway** [comment]
What about for commands that are supposed to return a `Chainable`? For example: 

```
function login(email: string, password: string): Cypress.Chainable<Chainable> {
  cy.request(options);
});

Cypress.Commands.add("login", login);
```

TypeScript won't allow us to _not_ return a value in command, and yet this is how most commands work.

**Comment by brian-mann** [comment]
Custom commands like this should always return a value. You should return `cy.request(...)` here.

**Comment by shcallaway** [comment]
What about [this example](https://docs.cypress.io/api/cypress-api/custom-commands.html#Parent-Commands), then?

**Comment by brian-mann** [comment]
It would technically work if all you're doing is enqueing more Cypress commands, but it would not work in other situations like if you return a regular Promise. So best practice would be to always return something.

We'll update the examples. It's not going to hurt anything by always returning from Custom Commands.

**Comment by shcallaway** [comment]
So in general I should return the last `cy` command in a custom command? Cypress will correctly enqueue all the commands that come before it?

**Comment by brian-mann** [comment]
Right so this is where it gets weird which is why we've opted not to return some things from the examples.

All that's happening when you do `cy.whatever` is that its literally **enqueuing** a command to run. IT doesn't actually do anything at that moment. No work is kicked off.

So the return value is only applicable do the current custom command. What I mean is, the `login` command resolves whenever the function finishes - or its awaited if a Promise is returned. Since `cy` commands return synchronous chainer objects then the command would finish immediately. 

The work of the other commands has just been enqueued, not run yet.

What happens is that it just looks weird...

```js
Cypress.Commands.add('foo', () => {
  cy.get(...)
  cy.get(...)
})

```

**Comment by shcallaway** [comment]
Given that the actual return value of the custom command has no purpose (outside of the custom command itself), why would I declare the return type to begin with? I could just do this:

```
function login(email: string, password: string): void {
  cy.request(options);
});

Cypress.Commands.add('login', login);
```

**Comment by brian-mann** [comment]
Yes, I suppose that is all you need. That should work fine. Unless the custom command returns things *other* than more cypress commands, it can return void.

**Comment by shcallaway** [comment]
For future readers, this is the TypeScript concept that makes it possible to re-declare the Cypress namespace: [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). 

Also, @NicholasBoll , regarding your example, what is the purpose of adding the generic?

**Comment by bahmutov** [comment]
I tried it out with Cypress 1.1.4 type definitions and this approach of merging Cypress interface works. https://github.com/cypress-io/snapshot/pull/11/files The new method becomes available on the interface, making TS and VSCode happy

**Comment by shcallaway** [comment]
Hmm I'm still getting errors (e.g. `Property 'goToPage' does not exist on type 'Chainable'.`). I don't think declaration merging is working — possibly because of these two lines in `cypress/index.d.ts`?

```
// global variables added by Cypress when it runs
declare const cy: Cypress.Chainable;
declare const Cypress: Cypress.Cypress;
```

Here is my `commands.ts`:

```
declare namespace Cypress {
  interface Chainable {
    goToPage: typeof goToPage;
    login: typeof login;
    getGridHeader: typeof getGridHeader;
    clearSession: typeof clearSession;
    logout: typeof logout;
    // ...
  }
}

const passSubject = { prevSubject: true };

Cypress.Commands.add("goToPage", goToPage);
Cypress.Commands.add("login", login);
Cypress.Commands.add("getGridHeader", getGridHeader);
Cypress.Commands.add("clearSession", clearSession);
Cypress.Commands.add("logout", logout);
// ...

function goToPage(path: string): void {
  // ...
}

// ...
```

Here is my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs"
  },
  "include": [
    "./*/*.ts",
    // explicitly include cypress types from node module
    "../node_modules/cypress"
  ]
}
```

And I don't think it matters, but here is my `plugins/index.js`:

```
const webpack = require("@cypress/webpack-preprocessor");
module.exports = (on, config) => {
  const webpackOptions = {
    resolve: {
      extensions: [".ts", ".js"]
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          loader: "ts-loader",
          options: {
            configFile: "tsconfig.cypress.json"
          }
        }
      ]
    }
  };

  on("file:preprocessor", webpack({
    webpackOptions: webpackOptions
  }));
};
```

**Comment by NicholasBoll** [comment]
> Also, @NicholasBoll , regarding your example, what is the purpose of adding the generic?

@shcallaway I added the Generic (should be available on Cypress 1.2.0, but not on Cypress 1.1.4) to allow they subject to be passed around so that the `.then` type would be known. For backwards compatibility, the Subject is defaulted to `any`. For example:

```ts
cy.wrap({ foo: 'bar' })
  .then(subject => {
    subject; // $ExpectType { foo: string }
  })
  .its('foo') // keyof type checked - 'foo1' would be a type error
  .then(subject => {
    subject; // $ExpectType string
  })
```
Without the generic, the subject would always be `any`

**Comment by NicholasBoll** [comment]
@shcallaway I knew that TypeScript merged declarations, but I didn't know they documented it. Thanks!

**Comment by shcallaway** [comment]
@NicholasBoll I don't think your PR on snapshot fully solves the problem of using custom commands with TypeScript. Specifically, it does not address:

1. The extremely common use case of using `cy` in `commands.ts`. The TS compiler insists that `myCustomCommand` does not exist on type `Chainable`, even after re-declaring the namespace and interface. I believe this is due to the `declare const cy: Cypress.Chainable` in `index.d.ts`.
2. The fact that, [as we determined earlier](https://github.com/cypress-io/cypress/issues/1065#issuecomment-351785734), most custom commands don't return anything. And yet users will naturally expect to be able to do something like this:

![image](https://user-images.githubusercontent.com/7094076/34019426-ac75d88e-e0e3-11e7-8c68-14c009956856.png)

**Comment by NicholasBoll** [comment]
A suggestion and I don't know how the Cypress team feels about it, but we don't use `Cypress.Commands.add` for actions we want to complete that don't return anything (`void`). It is a bit odd to type and if we don't return chainable methods it might not make sense. We just use function calls:

```ts
export function login(
  name: string,
  password?: string,
): void {
  cy.log(`Logging in as ${name}`);

  cy.request({
    method: 'POST',
    url: '/api/webconsole/login',
    body: {
      username: name,
      password: 'logrhythm!1',
    },
  }).then(response => {
    console.log(response);
    return response;
  });
}
```

In some other file:
```ts
import { login } from '../helpers/login'

describe('Login', () => {
  it('should allow the user to enter credentials', () => {
    login('username', 'password');

    cy.title().should('contain', 'Dashboard');
  });
});
```

**Comment by NicholasBoll** [comment]
I just checkout out the branch that @bahmutov provided: https://github.com/cypress-io/snapshot/pull/11/files and changed a few things to verify:

```ts
// commands.ts
// register .snapshot() command
require('../..').register()

// merge Cypress interface with new command "snapshot()"
declare namespace Cypress {
  interface Chainable {
    snapshot(): void
  }
}

declare namespace Cypress {
  interface Chainable {
    getBody: typeof getBody
  }
}

function getBody(): Cypress.Chainable {
  return cy.get('body')
}

Cypress.Commands.add('getBody', getBody)
```

```ts
// spec-typescript.ts
describe('@cypress/snapshot', () => {
  beforeEach(() => {
    cy.visit('https://example.cypress.io')
  })

  context('simple types', () => {
    it('works with objects', () => {
      cy.wrap({ foo: 42 }).snapshot()
    })

    it('works with numbers', () => {
      cy.wrap(42).snapshot()
    })

    it('works with strings', () => {
      cy.wrap('foo-bar').snapshot()
    })

    it('works with arrays', () => {
      cy.wrap([1, 2, 3]).snapshot()
    })

    it('should get the body tag', () => {
      cy.getBody().should('contain', 'Kitchen Sink')
    })
  })
})
```

That is working for me. `getBody` is known and can be chained.

**Comment by shcallaway** [comment]
😕 I must be doing something wrong then.

@NicholasBoll It's good that it works as expected, though.

**Comment by NicholasBoll** [comment]
@shcallaway Note the snapshot repo is using Cypress 1.1.4 which has no generic. 1.2.0 adds the `Subject` generic. This shouldn't effect any implementation, but if you are creating your own commands in TypeScript the interface declaration will change slightly:

```ts
declare namespace Cypress {
  interface Chainable<Subject> {
    getBody: typeof getBody
  }
}

// can omit return type - it is inferred - will be `Cypress.Chainable<JQuery<HTMLBodyElement>>`
function getBody() {
  return cy.get('body')
}
```

**Comment by NicholasBoll** [comment]
My steps were checking out the snapshot repo, checking out the branch and running `npm install`. I'm using VS Code. I'm curious to know why it isn't working for you.

Are you trying the snapshot repo?

Something to watch out for is your `tsconfig.json` needs to include files from `./cypress/support` (or where ever you've configured that folder). Here's the `tsconfig.json` for the snapshot repo:

```json
{
  "include": [
    "node_modules/cypress",
    "cypress/*/*.ts"
  ]
}
```

**Comment by shcallaway** [comment]
@NicholasBoll I'm working off my own app, not snapshot. It appears to be configured correctly though. You can see my files [here](https://github.com/cypress-io/cypress/issues/1065#issuecomment-351851576).

**Comment by shcallaway** [comment]
Note that I have tried _forcibly_ importing the Cypress types into my `commands.ts` by doing:

```
import "../../node_modules/cypress/index.d.ts";
```

Which results in a lot of these:

```
TS90010: Type 'Cypress.Chainable' is not assignable to type 'Cypress.Chainable'. Two different types with this name exist, but they are unrelated.
```

I believe these errors occur because the return type for custom commands is `Cypress.Chainable` but the return values is `cy`, and TS is not correctly merging my definition of `Cypress.Chainable` with the existing definition.

**Comment by NicholasBoll** [comment]
I got that same error when I used an `import` in `commands.ts`. I had to not have any import/export in that file (makes TypeScript treat as a module). Not sure why TS thinks they are unrelated in that case.

The `tsconfig` was a little tricky, but I think I'm doing it the same as you. My `tsconfig.json` looks like this:

`./cypress/tsconfig.json`
```json
{
  "compilerOptions": {
    "baseUrl": "../node_modules",
    "sourceMap": true,
    "target": "es2017",
    "strict": true,
    "moduleResolution": "node",
    "types": [
      "mocha"
    ],
    "lib": [
      "dom",
      "es2017"
    ]
  },
  "include": [
    "../node_modules",
    "**/*.ts"
  ]
}
```

Note the `baseUrl` and the `include` with `../node_modules`.

Also make sure you don't have `@types/cypress` lurking in your node_modules. I was getting duplicate and conflicting definitions. Those types are pre-1.0.

**Comment by NicholasBoll** [comment]
Normally TypeScript includes `node_modules`, but if the file isn't defined in the same directory as `node_modules`, I've had missing types.

I just noticed your `tsconfig.json` has `./*/*.ts`. I have `**/*.ts`. I don't know the subtleties of glob, but the globstar should include any number of directories. I consider that safer.

**Comment by bahmutov** [comment]
I just tried it from scratch in TS 2.6.2 and Cypress 1.4.1 and it seems to work, adding new commands https://github.com/cypress-io/add-cypress-custom-command-in-typescript 

I suspect there are other TS definitions in `node_modules` that somehow conflict or break TS compiler :(

**Comment by jogelin** [comment]
Any update with the version 2.x of cypress ?
I have the same issue:
```
Property login does not exist on type Chainable<undefined>
```

I am using cypress 2.1.0 and ts 2.7.1

Is [https://github.com/bahmutov/add-typescript-to-cypress](https://github.com/bahmutov/add-typescript-to-cypress) still necessary ? Ts seems to work without webpack preprocessor ....

**Comment by krzysztof-grzybek** [comment]
I fixed with adding `index.d.ts` file in my `commands` folder. In this file I added something like this:

```
import { MyCustomType } from '../Types';

declare global {
  namespace Cypress {
    interface Chainable<Subject = any> {
      login(): Chainable<MyCustomType>;
    }
  }
}
```
If You don't import or export anything, just omit global namespace declaration:

```
declare namespace Cypress {
  interface Chainable<Subject = any> {
    login(): Chainable<MyCustomType>;
  }
}

```
Keep in mind that it won't work with Typesciprt < 2.3, becuase default generics type has to be supported.

**Comment by brandonmp-cw** [comment]
I was having this problem. TS and custom Cypress commands were working fine, but I after I added another custom command, everything broke.

I think it was b/c I was importing something into my `cypress.d.ts` in the wrong spot.

```
//** I had been importing something here

declare namespace Cypress {
  import { SalesforceGetAccountArgs } from "../cypress/support/sf";
//** Moving it to here (within the declaration) fixed things, apparently
  import { CustomerIoMessage } from "../lib/customer-io";

  export interface Chainable<Subject> {
    sfGetAccount: (
      getAccountArgs: SalesforceGetAccountArgs
    ) => Chainable<Partial<SalesforceAccount>>;
   getSentEmails: (email: string) => Chainable<Array<CustomerIoMessage>>;
  }
}
```

**Comment by NicholasBoll** [comment]
Typescript is weird about mixing modules and namespaces: https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

Cypress uses a namespace. You can tell because you don't import `cy` to use the command. This is easier for JS development because you don't have to import anything. It is harder for Typescript development because now Typescript has to be told a namespace exists. Try moving your imports into the namespace as suggested here: https://github.com/cypress-io/cypress/issues/1065#issuecomment-420824544

**Comment by wajdibeltaifa** [comment]
@NicholasBoll @bahmutov what about using a custom command as a **child command** !

Consider this implementation  : 

`declare namespace Cypress {
  interface Chainable<Subject> {
    myCustomCommand: typeof myCustomCommand
  }
}

function myCustomCommand(value: string): Cypress.Chainable<JQuery> {
 // get previous subject here !
  ...
}

Cypress.Commands.add('myCustomCommand', myCustomCommand)
`
And the call of this command should be applied on the previous Subject like bellow : 

`cy.get(...).myCustomCommand(...)`

**The Question** : Haw can i have access to the **previous subject** on custom command as **child command** with **typescript** ?

**Comment by bahmutov** [comment]
You can provide TypeScript definitions for custom commands, even when using JavaScript in your specs
- https://docs.cypress.io/api/cypress-api/custom-commands.html#5-Write-TypeScript-definitions
- example code https://github.com/cypress-io/cypress-example-todomvc#cypress-intellisense
- slides around slide 27 in this presentation https://slides.com/bahmutov/ts-without-ts#/27 talk about adding definitions to your `cy` object

**Comment by spencermefford** [comment]
I had issues declaring the namespace when importing other files into `commands.ts`. I ran across this solution which worked for me:

https://github.com/cypress-io/add-cypress-custom-command-in-typescript/issues/2#issuecomment-389870033

Just wanted to help anyone else find that if they end up on this thread.

**Comment by vipulrawat** [comment]
I am using parcel instead to webpack, so can't use the webpack preprocessor. Is there any way to get the types of custom commands?

**Comment by NicholasBoll** [comment]
> I am using parcel instead to webpack, so can't use the webpack preprocessor. Is there any way to get the types of custom commands?

Cypress runs each of your test files in an isolated context. It doesn't matter that your app is bundled by Parcel. You can still use the webpack plugin for Cypress. You can use the browserify plugin. You can create a Parcel plugin instead. Typescript doesn't care which one you use either.

**Comment by vipulrawat** [comment]
Thanks @NicholasBoll. Didn't knew about this. It solved my issue.

**Comment by KarlaLopez1411** [comment]
Hi, guys, I follow all your recommendations but I got this error:
![Screen Shot 2019-10-11 at 12 45 36](https://user-images.githubusercontent.com/54606287/66676721-5e353080-ec25-11e9-9f69-9b186e414b36.png)

I'm trying to test a backend function.
Could someone help with this?

**Comment by stychu** [comment]
Dunno if this is solved but I ran in the same problem... Following official guides doesn't allow me pretty much for importing any custom types to cover for custom commands definition types.
However this seem to kind of work.

`// cypress/support/commands.ts`
```
import { ssoPageSelectors } from './pageSelectors'
import { IAccount } from '../data/users'

const logInAs = (account: IAccount) => {
  const { username, password } = account
  cy.visit('/')

  cy.assertElementExists(ssoPageSelectors.userNameInput)
    .type(username)
    .get('body')
    .then(($body) => {
      const passwordInput = $body.find(ssoPageSelectors.passwordInput).length

      if (!passwordInput) {
        cy.get(ssoPageSelectors.loginButton).click()
      }
    })
    .assertElementExists(ssoPageSelectors.passwordInput)
    .type(password)
    .assertElementExists(ssoPageSelectors.loginButton)
    .click()
}

const assertChildrenLength = (element: string, count: number) => {
  cy.assertElementExists(element).children().should('have.length', count)
}

const assertElementExists = (element: string) => {
  cy.get(element).should('exist')
}

const assertElementNotExists = (element: string) => {
  cy.get(element).should('not.exist')
}

const commands = [
  logInAs,
  assertChildrenLength,
  assertElementExists,
  assertElementNotExists,
]

commands.forEach((command) => Cypress.Commands.add(command.name, command))

```

`// cypress/support/types.d.ts`
```
/* eslint-disable unused-imports/no-unused-imports */
/* eslint @typescript-eslint/no-unused-vars: 0 */
/// <reference types="cypress" />

import { IAccount } from '../data/users'

declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Login with a given type of a user account
       * @param account - type of the account
       * @example
       * import { users } from '../../data/users'
       * cy.logInAs(users.ADMIN)
       */
      logInAs(account: IAccount): Cypress.Chainable<Element>

      /**
       * Asserts the length of children elements
       * @param element - selector as a string for element
       * @param count - expected count of child elements
       * @example
       * cy.assertChildrenLength('#element', 3)
       * cy.assertChildrenLength('.class', 3)
       */
      assertChildrenLength(
        element: string,
        count: number,
      ): Cypress.Chainable<Element>

      /**
       * Asserts that given element exists in the DOM
       * @param element - selector as a string for element
       * @example
       * cy.assertElementExists('#element')
       * cy.assertElementExists('.class')
       */
      assertElementExists(element: string): Cypress.Chainable<Element>

      /**
       * Asserts that given element exists in the DOM
       * @param element - selector as a string for element
       * @example
       * cy.assertElementExists('#element')
       * cy.assertElementExists('.class')
       */
      assertElementNotExists(element: string): Cypress.Chainable<Element>
    }
  }
}
```

**Comment by wiegell** [comment]
> I fixed it by adding `index.d.ts` file in my `commands` folder. In this file I added something like this:
> 
> ```ts
> import { MyCustomType } from '../Types';
> 
> declare global {
>   namespace Cypress {
>     interface Chainable<Subject = any> {
>       login(): Chainable<MyCustomType>;
>     }
>   }
> }
> ```
> 
> If You don't import or export anything, just omit global namespace declaration:
> 
> ```ts
> declare namespace Cypress {
>   interface Chainable<Subject = any> {
>     login(): Chainable<MyCustomType>;
>   }
> }
> ```
> 
> Keep in mind that it won't work with Typesciprt < 2.3, becuase default generics type has to be supported.

This worked, but the index and command files have to be .js files - i wrongly still had them as .ts , which gives comlilation errors.

**Comment by yogithesymbian** [comment]
> I fixed it by adding `index.d.ts` file in my `commands` folder. In this file I added something like this:
> 
> ```ts
> import { MyCustomType } from '../Types';
> 
> declare global {
>   namespace Cypress {
>     interface Chainable<Subject = any> {
>       login(): Chainable<MyCustomType>;
>     }
>   }
> }
> ```
> 
> If You don't import or export anything, just omit global namespace declaration:
> 
> ```ts
> declare namespace Cypress {
>   interface Chainable<Subject = any> {
>     login(): Chainable<MyCustomType>;
>   }
> }
> ```
> 
> Keep in mind that it won't work with Typesciprt < 2.3, becuase default generics type has to be supported.

you saved my life
before i have used like these and i am worries if i have a lot of data
```
// cypress/support/index.d.ts
declare namespace Cypress {

  interface LabelFixture {
    dashboard: string;
  }

  interface DataFixture {
    key1: string;
    key2: number;
    // Add more properties as needed
  }

  interface Chainable {
    loginCookies(user: { email: string; password: string }): Chainable<any>;
    logout(): Chainable<any>;
    setCustomViewport(): Chainable<any>;

    fixture(name: '1dashboard/label.json'): Chainable<LabelFixture>;
    fixture(name: '1dashboard/data.json'): Chainable<DataFixture>;
  }
}
```

so i use your code 
```
// now i can use import 
import DataFixture from '../fixtures/1dashboard/data.fixture'  // without break the chainable

declare global {
  namespace Cypress {
    interface Chainable<Subject = any> {
```
thankyou 🚀

**Comment by yogithesymbian** [comment]
> > I fixed it by adding `index.d.ts` file in my `commands` folder. In this file I added something like this:
> > ```ts
> > import { MyCustomType } from '../Types';
> > 
> > declare global {
> >   namespace Cypress {
> >     interface Chainable<Subject = any> {
> >       login(): Chainable<MyCustomType>;
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If You don't import or export anything, just omit global namespace declaration:
> > ```ts
> > declare namespace Cypress {
> >   interface Chainable<Subject = any> {
> >     login(): Chainable<MyCustomType>;
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Keep in mind that it won't work with Typesciprt < 2.3, becuase default generics type has to be supported.
> 
> you saved my life before i have used like these and i am worries if i have a lot of data
> 
> ```
> // cypress/support/index.d.ts
> declare namespace Cypress {
> 
>   interface LabelFixture {
>     dashboard: string;
>   }
> 
>   interface DataFixture {
>     key1: string;
>     key2: number;
>     // Add more properties as needed
>   }
> 
>   interface Chainable {
>     loginCookies(user: { email: string; password: string }): Chainable<any>;
>     logout(): Chainable<any>;
>     setCustomViewport(): Chainable<any>;
> 
>     fixture(name: '1dashboard/label.json'): Chainable<LabelFixture>;
>     fixture(name: '1dashboard/data.json'): Chainable<DataFixture>;
>   }
> }
> ```
> 
> so i use your code
> 
> ```
> // now i can use import 
> import DataFixture from '../fixtures/1dashboard/data.fixture'  // without break the chainable
> 
> declare global {
>   namespace Cypress {
>     interface Chainable<Subject = any> {
> ```
> 
> thankyou 🚀

then change to 
```
command.ts
Cypress.Commands.add("loadDashboardLabel", () => {
  return cy.fixture('1dashboard/label.json');
});
```
```
// cypress/support/index.d.ts
import DashboardData from '../fixtures/1dashboard/data.fixture'

declare global {
  namespace Cypress {
    interface Chainable<Subject = any> {
       loadDashboardLabel(): Chainable<DashboardLabel>;
```

**Comment by vijaycapsifi** [comment]
Thanks for the solution. Much appreciated!
