### ISSUE TITLE
[Cypress 16] Throw a curated error when `Cypress.env()` is called

### ISSUE THREAD

**Issue by mschile** [cypress-io/cypress#34570]
### What would you like?

Calling `Cypress.env()` on Cypress 16 should throw a curated Cypress error naming the removal and pointing at the migration path, instead of the native `TypeError: Cypress.env is not a function`.

`Cypress.env()` was removed in [#33963](https://github.com/cypress-io/cypress/pull/33963) (closes [#33889](https://github.com/cypress-io/cypress/issues/33889)). On `release/16.0.0` the property is simply never assigned — [`packages/driver/src/cypress.ts`](https://github.com/cypress-io/cypress/blob/release/16.0.0/packages/driver/src/cypress.ts#L313) now only sets `this.expose`, and the `env: any` class field left at [line 143](https://github.com/cypress-io/cypress/blob/release/16.0.0/packages/driver/src/cypress.ts#L143) is a dead declaration. So the only signal a user gets is the browser's native `TypeError`, which says nothing about the removal, the version it happened in, or what to use instead.

There is already a precedent for exactly this shape — a removed `Cypress.*` API, not a `cy.*` command. [`packages/driver/src/cypress/cookies.ts`](https://github.com/cypress-io/cypress/blob/release/16.0.0/packages/driver/src/cypress/cookies.ts#L72) keeps `Cypress.Cookies.preserveOnce()` and `Cypress.Cookies.defaults()` as stubs that throw `cookies.removed`:

> `Cypress.Cookies.preserveOnce()` was removed in Cypress version 12.0.0. Please update to use `cy.session()` instead.

The same pattern covers commands via [`packages/driver/src/cy/commands/xhr.ts`](https://github.com/cypress-io/cypress/blob/release/16.0.0/packages/driver/src/cy/commands/xhr.ts) (`server.removed` / `route.removed`), both still shipping on `release/16.0.0`.

Suggested equivalent, accounting for the two replacements depending on whether the value is sensitive:

> `Cypress.env()` was removed in Cypress version 16.0.0. Please update to use `Cypress.expose()` for non-sensitive values, or `cy.env()` for sensitive values that must remain in the Node process.

with `docsUrl: 'https://on.cypress.io/cypress-env-migration'`, matching the changelog entry and the migration guide.

### Why is this needed?

`Cypress.env()` is one of the most widely used APIs in the public surface, so this is the single most likely error a user hits when upgrading to 16. A native `TypeError` gives them nothing to search for and no link to follow — it reads like a Cypress bug rather than an intentional removal. The curated error is what makes the upgrade guide discoverable at the moment of failure.

This gap was called out when [#33889](https://github.com/cypress-io/cypress/issues/33889) was implemented ("Runtime calls to `Cypress.env(...)` on 16 will throw the native '`Cypress.env` is not a function' `TypeError` — no curated stub"), and again while writing the upgrade troubleshooting docs.

### Other

Implementation sketch (all paths against `release/16.0.0`):

- Add an `env.removed` (or similar) entry to `packages/driver/src/cypress/error_messages.ts` with the message above and the `cypress-env-migration` docs URL.
- Assign `Cypress.env` in `packages/driver/src/cypress.ts` as a stub that throws it via `$errUtils.throwErrByPath`, mirroring the `xhr.ts` pattern, and drop or retype the now-dead `env: any` field. It must be a plain throwing function rather than a `$SetterGetter` so that both the read form (`Cypress.env('FOO')`) and the write forms (`Cypress.env('FOO', 'bar')`, `Cypress.env({ ... })`) hit it.
- Leave the type definitions in `cli/types/cypress.d.ts` removed — the compile-time failure is the better signal for TS users
- Related, and worth deciding alongside this: `env` as a suite/test config override was removed in the same PR and now falls through to the generic [`invalid_test_override`](https://github.com/cypress-io/cypress/blob/release/16.0.0/packages/driver/src/cypress/error_messages.ts#L284) validation error. Consider special-casing the `env` key there to point at `expose: { KEY: value }`.
- Cover the getter and both setter forms in the driver specs, plus a `cy.origin()` case since the spec bridge constructs its own `Cypress` instance.
