### PR TITLE
chore: throw a curated error when `Cypress.env()` is called

### PR DESCRIPTION
**Pull request by mschile**
- Closes https://github.com/cypress-io/cypress/issues/34570

### Additional details

`Cypress.env()` was removed in #33963, but the property was simply never assigned — `packages/driver/src/cypress.ts` only set `this.expose`, and the `env: any` class field was left behind as a dead declaration. So the only signal a user got on upgrade was the browser's native `TypeError: Cypress.env is not a function`, which says nothing about the removal, the version it happened in, or what to use instead. Since `Cypress.env()` is one of the most widely used APIs in the public surface, this is the single most likely error a user hits when upgrading to 16, and a bare `TypeError` reads like a Cypress bug rather than an intentional removal.

**`Cypress.env()` now throws a curated error.** Following the existing precedent for removed `Cypress.*` APIs (`Cypress.Cookies.preserveOnce()`, `Cypress.Cookies.defaults()`, `Cypress.Server.defaults()`), a new `env.removed` entry in `error_messages.ts` names both replacements and links the migration guide:

```
`Cypress.env()` was removed in Cypress version 16.0.0. Please update to use `Cypress.expose()` for non-sensitive values, or `cy.env()` for sensitive values that must remain in the Node process.

The variable being accessed was: `FOO`
```

`docsUrl` is `https://on.cypress.io/cypress-env-migration`, matching the changelog entry and the migration guide. The stub reports the variable(s) being accessed so the call site is findable in a large suite — mirroring the wording of the `allowCypressEnv` error that shipped in 15.x. It covers all three call shapes: `Cypress.env('FOO')` and `Cypress.env('FOO', 'bar')` both report the single variable, `Cypress.env({ FOO, BAR })` reports both ("The variables being accessed were: `FOO`, `BAR`"), and bare `Cypress.env()` omits the line. Implemented as a plain throwing method rather than a `$SetterGetter`, so the read and write forms all hit it, and defined on the class rather than assigned in `configure()` so the `cy.origin()` spec bridge — which constructs its own `$Cypress` — is covered without extra wiring.

**`env` as a suite/test config override now errors too.** This was called out in the issue as worth deciding alongside. The `env` key was removed as a per-test/suite override in the same release, but its `overrideLevel` in `@packages/config` was left at `'any'`. The effect was worse than a confusing error: `it('...', { env: { FOO: 'bar' } })` was *silently accepted* and merged into the driver's config as an inert key (and became readable via `Cypress.config('env')`, which is otherwise stripped before serialization to the browser), so a JS user got no signal at all that their override did nothing. TS users were already covered — `env` is absent from `TestConfigOverrides` / `SuiteConfigOverrides`.

`env` is now `overrideLevel: 'never'`, and `validateConfig` routes the key to a dedicated `config.env_removed` message rather than the generic read-only error:

```
Overriding the `env` configuration was removed in Cypress version 16.0.0.

Please update to use `expose: { KEY: value }` to make a value readable in the browser for a suite or test.

https://on.cypress.io/cypress-env-migration
```

A dedicated error key was chosen over reusing the generic `read_only` message because "because it is a read-only configuration option" is inaccurate for `env` — it *is* settable globally in `cypress.config`, just not overridable per-test — and because the generic message links `/config` rather than the migration guide, which is the whole point of the change. `env` remains a valid global config option feeding `cy.env()`; only the override path changed.

Two things worth flagging for the reviewer:

- The migration link in `config.env_removed` is embedded in the **message text** rather than set as `docsUrl`. `validateConfig` throws these via `new (state('specWindow').Error)($errUtils.errByPath(...))`, which passes a `CypressError` *object* as a plain `Error`'s message — so `docsUrl` is dropped (and the message picks up a `CypressError: ` prefix, visible in the `issue_6407_spec` snapshot). Fixing that properly means touching every config-override error and updating that snapshot, which is out of scope here; there is precedent for a URL in the message body (`retries.manually_set_retries_test`). Happy to split the `docsUrl` fix into its own PR if preferred.
- Flipping `overrideLevel` is contained: `testOverrideLevels` has exactly two consumers, both in the driver — `validateOverridableAtRunTime` (the intended change) and `omitConfigReadOnlyDifferences`, which strips `'never'` keys during cross-origin config sync. The latter is inert here since the driver's config never carries `env`. No `data-context` / `app` / `launchpad` consumers, and the `@packages/config` snapshots only capture `defaultValues` and public key lists, not override levels.

Per-repo-guidance, no new changelog entry: 16.0.0 is unreleased and its existing breaking-change bullet already documents the `Cypress.env()` removal, both replacements, the `expose: { KEY: value }` guidance for overrides, and the migration guide link. This PR makes that already-documented removal discoverable at the moment of failure rather than introducing a separate user-facing change.

The type definitions in `cli/types/cypress.d.ts` are deliberately left removed — a compile-time failure is the better signal for TS users than a runtime throw.

---

> [!NOTE]
> **Low Risk**
> Behavior is intentionally breaking for upgrade paths already documented in Cypress 16; changes are limited to driver error handling and config override validation, not env storage or `cy.env()`.
> 
> **Overview**
> **Replaces the bare `TypeError` from removed `Cypress.env()` with a curated failure** that names Cypress 16, points to `Cypress.expose()` / `cy.env()`, lists accessed key(s), links the migration guide, and includes a plugin hint. A throwing `env()` method on `$Cypress` covers all call shapes (read, write, bulk, no-arg) and works in `cy.origin()` spec bridges; stack/code frames target the spec call site where supported.
> 
> **Stops silent acceptance of per-test/suite `env` overrides** by setting the `env` config option to `overrideLevel: 'never'` and routing validation to a dedicated `config.env_removed` message (use `expose: { KEY: value }` instead). Runtime `Cypress.config('env', …)` gets the same migration-oriented error rather than a generic read-only message. Global `env` in `cypress.config` is unchanged for `cy.env()`.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 05ba3e952c72c1aee72fee81b24c56604a877724. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### Steps to test

Driver e2e (requires `@packages/config` and `@packages/runner` to be rebuilt first — the `env` override tests fail against a stale `@packages/config` esm build):

```
yarn workspace @packages/config build
yarn workspace @packages/runner build
yarn workspace @packages/driver cypress:run -- --browser chrome --spec "cypress/e2e/commands/removed_commands.cy.js,cypress/e2e/util/config.cy.js,cypress/e2e/e2e/testConfigOverrides.cy.js,cypress/e2e/e2e/env.cy.ts,cypress/e2e/e2e/origin/config_env_expose.cy.ts"
```

To see it by hand, in any spec:

1. `Cypress.env('FOO')` → curated error naming `Cypress.expose()` / `cy.env()`, reporting `FOO`, linking the migration guide. Same for `Cypress.env('FOO', 'bar')` and `Cypress.env({ FOO: 'foo', BAR: 'bar' })`.
2. `it('...', { env: { FOO: 'bar' } }, () => {})` → the test fails pointing at `expose: { KEY: value }` instead of silently doing nothing.
3. Global `env` in `cypress.config` still feeds `cy.env()` — unchanged.

### How has the user experience changed?

image

image

image

Before, on 16: `Cypress.env('FOO')` failed with the browser's native `TypeError: Cypress.env is not a function`, and an `env` test-config override did nothing at all with no error.

After: both name the removal, the version, the replacement API, and link the migration guide. Full messages are quoted in the "Additional details" section above and asserted verbatim in `packages/driver/cypress/e2e/commands/removed_commands.cy.js`.

### PR Tasks

- [x] Is there an associated issue with maintainer approval for PR submission? 
- [x] Have tests been added/updated? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cypress.ts [hunk 1]
```diff
@@ -949,6 +948,18 @@ class $Cypress {
...
+  env (keyOrValues?: string | Record<string, any>) {
+    const keys = _.isObject(keyOrValues) ? Object.keys(keyOrValues) : _.compact([keyOrValues])
+    const specWindow = this.state?.('specWindow')
+
+    $errUtils.throwErrByPath('env.removed', {
+      args: { keys },
+      errProps: {
+        userInvocationStack: specWindow && $stackUtils.captureUserInvocationStack(specWindow.Error),
+      },
+    })
```
[the remark this answers is not in the document]
Comment (mschile) [reply packages/driver/src/cypress.ts:971]: I don't think this is valid, `getUserInvocationStack` does strip the appropriate frames.

File: packages/driver/src/cypress/error_messages.ts [hunk 2]
```diff
@@ -489,6 +496,20 @@ export default {
 
         > "{{error}}"`,
     },
+    removed ({ keys }: { keys: string[] }) {
+      const message = ['`Cypress.env()` was removed in Cypress version 16.0.0. Please update to use `Cypress.expose()` for non-sensitive values, or `cy.env()` for sensitive values.']
+
+      if (keys.length === 1) {
+        message.push(`The key being accessed was: \`${keys[0]}\``)
+      } else if (keys.length > 1) {
+        message.push(`The keys being accessed were: ${keys.map((key) => `\`${key}\``).join(', ')}`)
```
Comment (jennifer-shehane) [inline packages/driver/src/cypress/error_messages.ts:509]: I'd like to add this text as a paragraph before the docs link

```
This call may come from a plugin. Update the plugin to a version that supports Cypress 16.
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
I did verify that we print keys in cy.env, so printing keys does not diverge from our behavior here.

File: packages/driver/src/cypress/error_messages.ts (hunk 2 above)
Comment (mschile) [reply packages/driver/src/cypress/error_messages.ts:509]: I decided against the plugin text since we are including the code frame in the error message now which should point to the code (the stack trace would also include the plugin). But I'm fine with adding that text as well.

**Review by jennifer-shehane — APPROVED** [review]
Looks good. 

Image

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@mschile Actually, the array has an issue - I think this is related to the object/array thing we discussed earlier. The keys end up being the array keys.

Image

File: packages/driver/src/cypress/error_messages.ts (hunk 2 above)
Comment (mschile) [reply packages/driver/src/cypress/error_messages.ts:509]: Updated here: [f5c82ca](https://github.com/cypress-io/cypress/pull/34575/commits/f5c82cab870790b18cea6ce7ab6f7fb0f2a84d8e)

**Review by jennifer-shehane — APPROVED** [review]
working now

Image
