### ISSUE TITLE
Unable to use TypeScript 5.2.2 with Cypress

### ISSUE THREAD

**Issue by Furmanus** [cypress-io/cypress#27946]
### Current behavior

When trying to run cypress (v. 13.3.0) after upgrading TypeScript to 5.2.2 I'm getting following error:
```
> cypress run --browser chrome --headless


DevTools listening on ws://127.0.0.1:55721/devtools/browser/14f8fba2-9991-4a01-97ae-aab68abe63ce
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
Your configFile is invalid: <path_to_repo_here>/cypress.config.ts

It threw an error when required, check the stack trace below:

TSError: ⨯ Unable to compile TypeScript:
error TS5110: Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.

    at createTSError (/Users/<user>/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:311:16)
    at reportTSError (/Users/<user>/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:314:23)
(...rest of stack here)
```
Despite the fact that in my tsconfig.json both `module` and `moduleResolution` are set to NodeNext. See SO thread: https://stackoverflow.com/questions/77202439/typescript-5-2-2-with-cypress-js . After downgrading TypeScript to 5.1.6. Cypress is working fine. My project compiles and runs on TS 5.2.2 otherwise (except for cypress tests).

### Desired behavior

Cypress tests should run normally.

### Test code to reproduce

tsconfig.json:
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "removeComments": true,
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "esnext",
    "jsx": "react",
    "noEmitOnError": true,
    "allowSyntheticDefaultImports": true,
    "isolatedModules": true,
    "incremental": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "downlevelIteration": true,
    "resolveJsonModule": true
  },
  "include": [
    "./src/scripts/**/*"
  ]
}
```
cypress.config.ts contents:
```
import { defineConfig } from 'cypress';

export default defineConfig({
    e2e: {
        baseUrl: 'http://localhost:5020',
        specPattern: 'cypress/e2e/**/*.e2e-spec.ts',
    },
});

```

### Cypress Version

13.3.0

### Node version

18.16.1

### Operating System

macOS 13.4

**Comment by abieler-sap** [comment]
Actually it is not possible to use sourceMap with TypeScript 5.x. Try setting sourcMap to false in your tsconfig.json.
See https://github.com/cypress-io/cypress/issues/26203

**Comment by koooge** [comment]
I encountered the same error with cypress@12.17.4 and node16:

```
    "module": "node16",
    "moduleResolution": "node16",
```

```
TSError: ⨯ Unable to compile TypeScript:
error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.
```


The following workaround worked for me.
https://github.com/cypress-io/cypress/issues/26308#issuecomment-1663592648

**Comment by zeid0ne** [comment]
steal having  this problem with typescript 5.5.3 and cypress 13.13.0
