### ISSUE TITLE
Update to @cypress/vite-dev-server@2.2.3 breaks CI

### ISSUE THREAD

**Issue by xmatthias** [cypress-io/cypress#21435]
### Current behavior

Tests in CI fail (tests are working fine with @cypress/vite-dev-server@2.2.2)
```
/usr/local/bin/yarn serve
yarn run v1.22.18
$ vite

  vite v2.9.8 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 411ms.

[2690:0511/084710.575030:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
Your pluginsFile is invalid: /home/runner/work/frequi/frequi/cypress/plugins/index.js

It threw an error when required, check the stack trace below:

Error: Cannot find module 'fs/promises'
Require stack:
- /home/runner/work/frequi/frequi/node_modules/@cypress/vite-dev-server/dist/makeCypressPlugin.js
- /home/runner/work/frequi/frequi/node_modules/@cypress/vite-dev-server/dist/resolveServerConfig.js
- /home/runner/work/frequi/frequi/node_modules/@cypress/vite-dev-server/dist/index.js
- /home/runner/work/frequi/frequi/node_modules/@cypress/vite-dev-server/index.js
- /home/runner/work/frequi/frequi/cypress/plugins/index.js
- /home/runner/.cache/Cypress/9.6.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
- /home/runner/.cache/Cypress/9.6.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/home/runner/.cache/Cypress/9.6.1/Cypress/resources/app/packages/server/node_modules/tsconfig-paths/lib/register.js:75:[40](https://github.com/freqtrade/frequi/runs/6384695006?check_suite_focus=true#step:9:40))
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/frequi/frequi/node_modules/@cypress/vite-dev-server/dist/makeCypressPlugin.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/home/runner/.cache/Cypress/9.6.1/Cypress/resources/app/node_modules/ts-node/src/index.ts:529:[44](https://github.com/freqtrade/frequi/runs/6384695006?check_suite_focus=true#step:9:44))
    at Module.load (internal/modules/cjs/loader.js:8[63](https://github.com/freqtrade/frequi/runs/6384695006?check_suite_focus=true#step:9:63):32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/frequi/frequi/node_modules/@cypress/vite-dev-server/dist/resolveServerConfig.js:10:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

### Desired behavior

Tests should pass

### Test code to reproduce

Link to the failing CI: https://github.com/freqtrade/frequi/runs/6384695006?check_suite_focus=true

### Cypress Version

9.6.1

**Comment by mjhenkes** [comment]
@xmatthias, Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

**Comment by yann-combarnous** [comment]
Same thing here, CT breaks with latest vite-dev-server 2.2.3, works fine in 2.2.2 @mjhenkes .
