### ISSUE TITLE
Error when running "cypress open"

### ISSUE THREAD

**Issue by ahmed0saber** [cypress-io/cypress#32398]
### Current behavior

When I run "cypress open", I expect the cypress app to open, but it fails and throws an error as shown in the following figure.

<img width="1045" height="507" alt="Image" src="https://github.com/user-attachments/assets/93e70c0e-c261-4fcc-bae9-b7c394bbf26f" />

### Debug logs

```Text
PS F:\cypress project> npm run cy:open

> cy:open
> cypress open



DevTools listening on ws://127.0.0.1:63073/devtools/browser/cb954276-77c6-4669-b02e-b94c42dc9d03
<<<CYPRESS.STDERR.START>>>node:internal/modules/esm/resolve:265
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\IT' imported from F:\cypress project\
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:322:34)
    at loadESM (node:internal/process/esm_loader:23:33)
    at runMainESM (node:internal/modules/run_main:98:21)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:131:5) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Users/IT'
}

Node.js v20.12.2
<<<CYPRESS.STDERR.END>>>
```

### Cypress Version

15.0.0

### Node version

20.12.2

### Package Manager

npm

### Package Manager Version

10.8.0

### Operating system

Windows

### Operating System Version

10

### Other

Cypress v14.2.0 works fine with me.

My windows account user name is "IT SHOP", which makes the issue, as Cypress is trying to get something from a path containing "IT SHOP", but it fails to read it as "IT SHOP", it fails to read the space in the middle and just read "IT".

One solution is to change my user name, but my user name works fine on Cypress v14.2.0 and shouldn't be an issue, so this issue has been introduced in a newer version.

Maybe Cypress concatenates the account user name into a path to use it in the terminal without putting the whole path into string quotes.

**Comment by AtofStryker** [comment]
Hi @ahmed0saber. I think this has to do with your `CYPRESS_CACHE_PATH` having a space in it on Windows. I am working on a fix now and it should be released in Cypress `15.1.0`

**Comment by ahmed0saber** [comment]
Thanks @AtofStryker for checking it, I will be waiting for Cypress `15.1.0` then.
