### ISSUE TITLE
Open in IDE from Error block in open mode does not work.

### ISSUE THREAD

**Issue by isklep** [cypress-io/cypress#22239]
### Current behavior

Click on "open in IDE" in error report on Open mode does not working after update to 10.
macOS 12.4 
cypress 10.0.3
Browser Chrome 102
IDE VSCode

### Desired behavior

Open Ide https://share.merce.com/files/0Fg7SnEYLg.png

### Test code to reproduce

TypeError
cy.shouldSeeProductContactFormEmailValidationMessage is not a function
[../cypress/e2e/product_contact.js:23:16](http://...cloud/__/#)

### Cypress Version

10.0.3

**Comment by lmiller1990** [comment]
Hi! Are you able to reproduce while running with `DEBUG=cypress*` and see if there's anything logged when it fails to open? I was not able to reproduce on my mac.
