### ISSUE TITLE
Plugins file fails on lodash import after upgrade to 7.1.0

### ISSUE THREAD

**Issue by kubijo** [cypress-io/cypress#16111]
### Current behavior
When I upgrade my cypress instance from `6.8.0` to `7.1.0` I get an error where cypress thinks that my plugins file has invalid syntax, but the root cause is that it can't import `lodash` that I use for deep merge of default & our settings.

This used to work fine & I've tried to mitigate this by creating a custom importer akin to this: https://stackoverflow.com/questions/62298396/making-a-dependencys-dependencies-available-with-yarn-2/64242991#64242991 …alas it didn't help

I do have `lodash` installed in the root "workspace".

```
**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `…/web-ui/cypress/plugins/index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** Error: Cannot find module 'lodash'
Require stack:
- …/web-ui/cypress/plugins/index.ts
- /home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
- /home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/dev/…/pool/web-ui/cypress/plugins/index.ts:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at runPlugins (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:175:15)
    at Object.<anonymous> (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

**Stack trace:**
```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `…/web-ui/cypress/plugins/index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/errors.js:988:15)
    at EventEmitter.<anonymous> (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/index.js:154:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/…/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Test code to reproduce
I've tried to reproduce this in the `cypress-test-tiny`, but wasn't able to… if you can point me in some direction I'll provide what's needed

### Versions
- Operating System: Ubuntu 20.10
- Cypress: 7.1.0
- Yarn: 2.4.0-git.20210226.hash-97663a9d with P'n'P enabled & workspaces setup
- Typescript: 4.2.3

**Comment by lmiller1990** [comment]
Did anything else change other than upgrading cypress? Could you try 6.9 and other version to try isolating the specific version that breaks things?

**Comment by kubijo** [comment]
No, just this ... I remember trying 7.0, and it was doing this as well, but I'll try now again

**Comment by kubijo** [comment]
`6.9.1` is OK, `7.0.0` has the reported problem plus it starts very slowly, and it reports some new issues to STDOUT

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:192669) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
```

**Comment by jennifer-shehane** [comment]
@kubijo We'll need a reproducible example in order to look into this. If you can isolate this and provide a repo. There is likely something more involved than just importing lodash, since you mention using workspaces.

**Comment by lmiller1990** [comment]
Good to know 6.9.1 -> 7.0.0 is the "breaking point". Happy to take a look once we have a little more info to go on as mentioned above!

PS: the slow startup issue is under investigation. 👍 Cypress will be nice and fast again soon.

**Comment by titenis** [comment]
having same problem after upgrading to 7 with webpack preprocessor or any other require in plugins file
`Error: Cannot find module '@cypress/webpack-preprocessor'`
latest 6 version works fine. Only thing that looks like changed is 
> The bundled Node.js version was upgraded from 12.18.3 to 14.16.0. This could change the behavior of code within the pluginsFile when using the bundled Node.js version of Cypress.

**Comment by lmiller1990** [comment]
I tried importing lodash in a simple app using Cypress 7 and node.js 14 but I had no problems: https://github.com/lmiller1990/cypress-react-template/blob/18355f7093250eee85e5f021785baffb62643b62/cypress/plugins/index.js#L3-L7

Will need a reproduction repo to debug this further.

**Comment by brandonchinn178** [comment]
I have a repro, it seems to break between Cypress 6.9.1 -> 7.0.0 using Yarn 2, possibly related to https://github.com/cypress-io/cypress/issues/8008.

```bash
mkdir foo
cd foo
yarn set version berry
yarn init
yarn add -D cypress lodash

// have cypress initialize file structure
yarn cypress open

echo 'const _ = require("lodash")' >> cypress/plugins/index.js

// succeeds
yarn node cypress/plugins/index.js

// fails
yarn cypress open
```

**Comment by brandonchinn178** [comment]
I'm printing out
```js
console.log(module)
console.log(process)
```
in `plugins/index.js` and comparing the output between Cypress 6.9.1 and Cypress 7. One thing that stands out is that `process.versions` for Cypress 6.9.1 contains `pnp: '3'`, while Cypress 7 does not have `pnp` at all.

Where does Cypress get the Node executable from? I'm assuming Cypress has Node.js bundled somewhere and is using that `node` instead of whatever a user has installed.

**Comment by lmiller1990** [comment]
I had a poke around but I don't see any place that would be changed. Are you able to make a minimal reproduction (using yarn and the pnp feature, I guess?)

**Comment by brandonchinn178** [comment]
The repro is two comments up: https://github.com/cypress-io/cypress/issues/16111#issuecomment-864185387

**Comment by lmiller1990** [comment]
I cannot get this to work, am I misunderstanding how yarn 2 works?

```
$ yarn init
{
  name: 'lodash-yarn2'
}
$ yarn add -D cypress lodash

Usage Error: The nearest package directory (/Users/lachlan/code/dump/reproductions/lodash-yarn2) doesn't seem to be part of the project declared in /Users/lachlan/code/dump.

- If the project directory is right, it might be that you forgot to list reproductions/lodash-yarn2 as a workspace.
- If it isn't, it's likely because you have a yarn.lock or package.json file there, confusing the project root detection.

$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] ...
```

**Comment by lmiller1990** [comment]
I missed that, sorry.

I created a new project using yarn 2, installed lodash, `yarn cypress open`:

Seems okay 🤔 

![image](https://user-images.githubusercontent.com/19196536/122720864-53181c00-d2b3-11eb-934b-1fa2a85f0c5a.png)

Maybe I missed something?

**Comment by brandonchinn178** [comment]
hm you ran `yarn cypress open`? whats the output of `yarn --version`? and while we're at it, what's `node --version`?

**Comment by lmiller1990** [comment]
```
$ yarn --version
2.4.2
$ node --version
v14.16.0
$ yarn node --version
v14.16.0
```

**Comment by brandonchinn178** [comment]
https://www.loom.com/share/07f7e78338c74beca6e9490dcc611ab0

I'm not sure what you're doing, but it's failing consistently for me when I work in a completely new project

**Comment by lmiller1990** [comment]
So weird - I followed your reproduction side by side - I can't seem to reproduce it.

Here's a video. It's kind of long (`yarn add -D cypress` takes 1m+ on my machine).

**Comment by brandonchinn178** [comment]
Well the immediate thing that stands out was you misspelled `berry` in `yarn set version verry`. Is your global `yarn` version 2? That's not how it normally works; the global yarn should be v1 and only v2 per-project.

I have it repro'd in Docker, does that work for you?

```dockerfile
FROM node:14

RUN apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

WORKDIR /src
RUN yarn set version berry
RUN yarn init
RUN yarn add -D cypress lodash

RUN echo '{}' > cypress.json
RUN mkdir -p cypress/integration cypress/plugins
RUN touch cypress/integration/foo.spec.js
RUN echo 'const _ = require("lodash")' > cypress/plugins/index.js

RUN yarn node cypress/plugins/index.js
RUN yarn cypress run
```

```bash
docker build - < Dockerfile
```

**Comment by lmiller1990** [comment]
🤦  on misspelling. That said, it's still using Yarn 2, so it should be the same?

I will give this a try.

**Comment by brandonchinn178** [comment]
I'm not sure.. the fact that you have a global `yarn` command using v2 seems to indicate to me that you're already in a yarn environment, which might have `lodash` installed?

**Comment by lmiller1990** [comment]
I ran into a similar problem over the weekend when trying to start component testing (which also imports modules in `plugins`). I think your suspicion about the issue been related to (https://github.com/cypress-io/cypress/issues/8008#issuecomment-673699986)https://github.com/cypress-io/cypress/issues/8008#issuecomment-673699986) is correct.

Yarn 2 is causing me a lot of problems so I just changed to npm (not happy about it). I don't know much about Yarn 2 but it looks like someone (either Cypress, community, or both) needs to throw some weight behind getting everything working with Yarn 2.

**Comment by missing1984** [comment]
Tried did into the code, this is an regression introduced by https://github.com/cypress-io/cypress/pull/15292 

Yarn pnp rely on node_options env variable to work. Prior to 7.0.0, we restored the node_options in the process that build plugin files so yarn pnp is able to pick that up.  The logic was removed in #15292 and therefore caused this issue.

@flotwig i saw you made the change, would that be possible to bring the node_options restore logic back? I think it make sense for plugin access what user set in their node_options
