### ISSUE TITLE
Error: Webpack Compilation Error in cypress 6.5.0

### ISSUE THREAD

**Issue by QualityACBJ** [cypress-io/cypress#15110]
Error: Webpack Compilation Error
./cypress/integration/site/headers/selectacity.js
Module build failed (from /Users/rbalachandran/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/rbalachandran/dev/code/bizjournals/node_modules/babel-preset-stage-2/lib/index.js

**Comment by dotwork** [comment]
I just updated to version 6.5.0 and am getting this error:

`[19:02:04][Step 3/3] Oops...we found an error preparing this test file:
[19:02:04][Step 3/3] 
[19:02:04][Step 3/3]   cypress/support/index.js
[19:02:04][Step 3/3] 
[19:02:04][Step 3/3] The error was:
[19:02:04][Step 3/3] 
[19:02:04][Step 3/3] Error: Webpack Compilation Error
[19:02:04][Step 3/3] ./cypress/support/index.js
[19:02:04][Step 3/3] Module build failed (from /home/teamcity/.cache/Cypress/6.5.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
[19:02:04][Step 3/3] Error: Plugin/Preset files are not allowed to export objects, only functions. In /home/teamcity/BuildAgent/work/616876f8a3120d42/node_modules/babel-preset-es2015/lib/index.js
[19:02:04][Step 3/3] 
[19:02:04][Step 3/3] This occurred while Cypress was compiling and bundling your test code. This is usually caused by:
[19:02:04][Step 3/3] 
[19:02:04][Step 3/3] - A missing file or dependency
[19:02:04][Step 3/3] - A syntax error in the file or one of its dependencies
[19:02:04][Step 3/3] `

This is all the code in my `cypress/support/index.js` file:
`// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')


Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test during uncaught exceptions in the application
  // return false;
})
`

**Comment by QualityACBJ** [comment]
Please can some one help with this issue. I am unable to resolve the issue

**Comment by dotwork** [comment]
It appears the issue was introduced after version 4.9.0. I reverted to version 4.8.0 to confirm the error disappeared. Then tried upgrading to different versions to test it out. The error appeared when I upgraded from 4.9.0 to version 5.0.0.

**Comment by QualityACBJ** [comment]
In 4.9 I was getting this error that the reason i update to 6.5.0 
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: Parse Error
Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
