### ISSUE TITLE
[@cypress/react] - Can't resolve '@cypress/react/support' using v5.7

### ISSUE THREAD

**Issue by Vadorequest** [cypress-io/cypress#16471]
After upgrading `@cypress/react` from v4.16 to v5.7, starting cypress yields:

```
Error: Webpack Compilation Error
./cypress/support/index.js
Module not found: Error: Can't resolve '@cypress/react/support' in '/Users/vadorequest/dev/NRN/v2-mst-aptd-at-lcz-sty/cypress/support'
resolve '@cypress/react/support' in '/Users/vadorequest/dev/NRN/v2-mst-aptd-at-lcz-sty/cypress/support'
  Parsed request is a module
  using description file: /Users/vadorequest/dev/NRN/v2-mst-aptd-at-lcz-sty/package.json (relative path: ./cypress/support)
    Field 'browser' doesn't contain a valid alias configuration

```

#### `cypress/support/index.js`
```js
// ***********************************************************
// This example support/index.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************

// See https://dev.to/cuichenli/how-do-i-setup-my-nextjs-development-environment-2kao
import '@cypress/react/support';
import './commands';

// See https://docs.cypress.io/api/events/catalog-of-events.html#Uncaught-Exceptions
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  console.error('Application error caught:', err, runnable);
  return false;
});

```

I tried changing to `import '@cypress/react';`, and then got new errors about ` Error: cy.visit from a component spec is not allowed`, although I'm testing pages, not components. I've probably missed something in the https://docs.cypress.io/guides/references/changelog#7-0-0 notes.

---

I wasn't aware to find the changelog for the `@cypress/react` package, it's probably buried somewhere in the monorepo.

Could you change the NPM description for `@cypress/react` to link to the changelog for that particular package? It'd make upgrade smoother.

**Comment by jennifer-shehane** [comment]
There's a changelog for @cypress/react within the package itself in the repo: https://github.com/cypress-io/cypress/blob/develop/npm/react/CHANGELOG.md

Did you walk through the migration guide for component testing? https://docs.cypress.io/guides/references/migration-guide#Component-Testing

**Comment by Vadorequest** [comment]
Thank you for the links, I'll take a deeper look later.

I still believe it could be made easier for developers to find the changelog when upgrading. I personally use `yarn upgrade-interactive --latest` and the link shown there is not helpful, and finding it "by myself" led me here. 😅

**Comment by lmiller1990** [comment]
You don't need `@cypress/react/support` anymore, just delete that line and you should be good. Here's one of my test projects using the latest versions of everything, you could take a look at that for inspiration: https://github.com/lmiller1990/cypress-react-template.

We also have a bunch more exmaples here for React _+ webpack/vite: https://github.com/cypress-io/cypress-component-examples/tree/main/create-react-app

Let me know if you have problems even after deleting that import

**Comment by Vadorequest** [comment]
Thanks! I didn't notice this line should have been deleted from the migration guide, I'll take a closer look at your repo!

**Comment by Vadorequest** [comment]
I managed to make Cypress v7 work. But I didn't succeed configuring the Components, though.

Also, I didn't find a good article about **why** using Cypress tests components, a lot of "how", but I lack a good reason to invest more time into it.

And, my setup is using Next.js, and it's quite different from https://github.com/lmiller1990/cypress-react-template, one of my issue was locating the webpack file, I don't have a webpack file since it's managed by Next.js internally.

**Comment by lmiller1990** [comment]
Hi! There's a bit on *why* component testing might be useful in [this blog post](https://www.cypress.io/blog/2021/04/06/introducing-the-cypress-component-test-runner/). It can be convenient to test component in isolation - although not everyone needs this feature.

There's a setup guide for [next.js](https://docs.cypress.io/guides/component-testing/framework-configuration#Next-js-Webpack-4), and a completed next.js example [here](https://github.com/cypress-io/cypress-component-examples).

Let me know if you'd like more info or get stuck, should you choose to explore component testing more. 🎉
