### PR TITLE
Fix typescript iterator error.

### LINKED ISSUE #7098: TypeError Array(...).keys(...).slice is not a function after upgrade from 3.8.3 to 4.4.1
### Current behavior:

I am using Cypress on an Angular application.

The following test is working on version 3.8.3

```js
it('cy.get() - query DOM elements', () => {
  let x = [...Array(100).keys()].map(x => x + "");
  cy.server().route('/test', x);
  cy.get('[data-cy=landmark]').invoke('text').should('contain', 'Welcome');
})
```

**but throws an error on 4.4.1**

```
TypeError: Array(...).keys(...).slice is not a function
    at Context.<anonymous> (http://localhost:4200/__cypress/tests?p=cypress/integration/examples/querying.spec.js-628:8:35)
```

### Test code to reproduce

Repository demonstrating the problem: https://github.com/Kimserey/cypress-test-issue
- branch `master` is 3.8.3
- branch `upgrade-4` is 4.4.1

1. From the root directory, run `ng serve`,
2. From the root directory, start cypress `npx cypress open`,
3. The only test in the integration specs will throw the TypeError.

## Versions

Cypress 4.4.1

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #7098

### User facing changelog

TypeScript transpiles iterators incorrectly when `--downlevelIterator` option is not given. Fixed it in cypress-browserify-preprocessor and applied it.

#### Why was this change necessary?

To fix the false failure.

#### What is affected by this change?

N/A

#### Any implementation details to explain?

A test is added in browserify-preprocessor. But added one more test to `browserify_typescript_passing_spec.ts` to check if it works correctly in cypress.

### How has the user experience changed?

Iterators work OK.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
Flaky failure.
