### ISSUE TITLE
9.1.0 fails with type error for browser icons

### ISSUE THREAD

**Issue by NigelGreenway** [cypress-io/cypress#20501]
### Current behavior

I run Cypress in my CI step and it fails due a type error.

```shell
[STARTED] Task without title.
[SUCCESS] Task without title.
$ npm run build
> website@0.1.0 build
> next build
info  - Checking validity of types...
Failed to compile.
./cache/Cypress/9.1.0/Cypress/resources/app/packages/ui-components/src/index.tsx:1:40
Type error: Cannot find module './browser-icon' or its corresponding type declarations.
> 1 | export { default as BrowserIcon } from './browser-icon'
    |                                        ^
  2 | 
  3 | export { default as Dropdown } from './dropdown'
```

### Desired behavior

The Cypress tests should run and fail only on a tests that doesn't pass.

### Test code to reproduce

Using gitlab CI and the Docker:dind service, use the following job config:

```yml
specification:
  tags:
    - test
  stage: test
  image: cypress/browsers:node16.13.2-chrome97-ff96
  script:
    - npm ci --no-audit --no-fund --prefer-offline
    - $(npm bin)/cypress verify
    - npm run build
    - npm run test.specifications.ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    reports:
      junit: cypress-junit.xml
    expire_in: 1 day
```

### Cypress Version

9.1.0

### Other

This works fine with the latest release of 8.2.0 and also 9.0.0. this starts to fail in 9.1.0 and was noticed when I upgraded from 8.2.0 to 9.5.1.
