### ISSUE TITLE
Webpack Compilation Error: Cannot find module - Babel dependency when `.babelrc` defines plugins

### ISSUE THREAD

**Issue by tyagow** [cypress-io/cypress#8364]
### Current behavior:
The test doesn't start and an error message is displayed
![image](https://user-images.githubusercontent.com/700778/90767164-18280f00-e2c3-11ea-9df5-fe5702f225e2.png)

![image](https://user-images.githubusercontent.com/700778/90769073-085dfa00-e2c6-11ea-8079-d4808c155c05.png)

### Desired behavior:

Test work as they were in version 4.12

### Test code to reproduce
 ?

### Versions

Cypress 5.0 
Ubuntu 20.04

**Comment by jennifer-shehane** [comment]
Can you provide any of the code you have included for preprocessing? The plugins/index.js, package.json, support files, etc? Thanks!

**Comment by Hypercubed** [comment]
I've had the same issue.  I've not been able to repo on a freash install... it happens when I upgrade from 4.3 to 5.0 within an existing angualr project that uses webpack (4.43.0) and typescript (3.5.3).  I suspect there is some conflict between my procjets webpack/typescript install or config and what cypress is using.

I'm using the following cypress plugins:

```
    "cypress-file-upload": "^3.4.0",
    "cypress-plugin-signalr": "^1.3.0",
    "cypress-terminal-report": "^1.2.1",
    "cypress-wait-until": "^1.6.1",
```

**Comment by Hypercubed** [comment]
@tyagow Do you happen to have a `.babelrc` in your project root.  That seams to be the issue for me.

**Comment by Hypercubed** [comment]
@jennifer-shehane Adding a `.babelrc` file to the root folder causes the error above.  For example:

```
{
  "presets": [
  ],
  "plugins": [
    "transform-runtime"
  ],
  "comments": true,
  "sourceMaps": true
}
```

**Comment by jennifer-shehane** [comment]
I'm able to recreate this with the presence of the `.babelrc` file at the root of my project with the reference to the `transform-runtime` plugin. Didn't seem to matter what babel plugins I actually had installed - I never got it to a running state. 

`.babelrc`

```yml
{
  "plugins": [
    "transform-runtime"
  ]
}
```

Run `cypress open` and click on a spec file or `cypress run`.

<img width="1638" alt="Screen Shot 2020-08-21 at 10 44 15 AM" src="https://user-images.githubusercontent.com/1271364/90851918-226a0c00-e39c-11ea-830a-6d17f54c602f.png">

**Comment by ztsmith** [comment]
adding an empty `.babelrc` file to the cypress directory allowed me to work around this issue. 
i.e. `cypress/.babelrc`
```
{}
```

**Comment by leandrotk** [comment]
I have the same error while running with `.babelrc`. This is what I'm using in my current project:

```json
{
  "plugins": ["styled-components", "transform-decorators"],
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": ["last 2 versions", "> 0.5% in BR", "iOS >= 9.3"]
        },
        "useBuiltIns": "entry"
      }
    ],
    "react",
    "stage-0"
  ],
  "env": {
    "development": {
      "plugins": ["babel-plugin-styled-components"]
    },
    "production": {
      "plugins": [
        "transform-react-remove-prop-types",
        "transform-react-constant-elements",
        "transform-react-inline-elements",
        "syntax-dynamic-import"
      ]
    },
    "test": {
      "presets": ["env", "react"],
      "plugins": [
        "transform-es2015-modules-commonjs",
        "transform-class-properties",
        "dynamic-import-node",
        "syntax-dynamic-import"
      ]
    }
  }
}
```

Adding an empty `.babelrc` inside the `/cypress` folder didn't work for me.

**Comment by arushirawal20** [comment]
> adding an empty `.babelrc` file to the cypress directory allowed me to work around this issue.
> i.e. `cypress/.babelrc`
> 
> ```
> {}
> ```

I tried the same but its still not working for me. Any other option ?

**Comment by mrvudo** [comment]
> adding an empty `.babelrc` file to the cypress directory allowed me to work around this issue.
> i.e. `cypress/.babelrc`
> 
> ```
> {}
> ```

I managed to get Cypress working with by adding .babelrc and using this package:

https://www.npmjs.com/package/@cypress/webpack-preprocessor#use-babelrc

**Comment by portothree** [comment]
Changing from `browserlist` to `.browserlistrc` fixed a similar error with the babel-loader for me

**Comment by roopat** [comment]
Adding an empty .babelrc in cypress/.babelrc didnt help me...can some one help me out with a working solution for this ?

**Comment by chloe0592** [comment]
@jennifer-shehane We are experiencing the same issue with the latest Cypress version and it's currently a blocker for our testing. Please provide a workaround or some additional info on how can we run our tests.

<img width="1336" alt="Screenshot 2020-10-27 at 15 30 34" src="https://user-images.githubusercontent.com/52276952/97316208-c6bf7180-1869-11eb-89f7-b72820333a54.png">

**Comment by Majd-iya** [comment]
> adding an empty `.babelrc` file to the cypress directory allowed me to work around this issue.
> i.e. `cypress/.babelrc`
> 
> ```
> {}
> ```

Worked for me either , thanks

**Comment by chloe0592** [comment]
I tried with `.babelrc` , and no luck.. I still get the same error.

**Comment by Majd-iya** [comment]
> I tried with `.babelrc` , and no luck.. I still get the same error.

Share Dependencies please

**Comment by chloe0592** [comment]
I found this for babel:
`"babel": {
        "plugins": [
            "@babel/plugin-proposal-class-properties",
            "@babel/plugin-syntax-dynamic-import"
        ],
        "presets": [
            "@babel/preset-env",
            "@babel/preset-react"
        ]
    },`

**Comment by Majd-iya** [comment]
> I found this for babel:
> `"babel": { "plugins": [ "@babel/plugin-proposal-class-properties", "@babel/plugin-syntax-dynamic-import" ], "presets": [ "@babel/preset-env", "@babel/preset-react" ] },`

what is your cypress dependency version ?

**Comment by chloe0592** [comment]
I've found the solution - I manually installed babel dependencies and updated again Cypress. Now the workaround with `.babelrc` works. Thanks @Majd-iya.

**Comment by Majd-iya** [comment]
> I've found the solution - I manually installed babel dependencies and updated again Cypress. Now the workaround with `.babelrc` works. Thanks @Majd-iya.

Happy for you :) enjoy coding :) @chloe0592

**Comment by brandon-leapyear** [comment]
I'm getting the same problem with `babel.config.js`, except what I'm doing is trying to upgrade to Yarn v2. Cypress has been working for us fine, but with Yarn v2 (and presumably its new Plug-n-Play restrictions) I'm getting errors loading babel plugins defined in `babel.config.js`

This seems like a regression from https://github.com/cypress-io/cypress/issues/312. I also tried adding `cypress/babel.config.js` with `module.exports = {}`, but I still get errors. Deleting `babel.config.js` goes further, but I get another error (which I'll open a separate ticket about)

**Comment by jennifer-shehane** [comment]
@brandon-leapyear The yarn 2 issues may be unrelated to this thread, not sure since you didn't post your error. See https://github.com/cypress-io/cypress/issues/6377

**Comment by brandon-leapyear** [comment]
So actually https://github.com/cypress-io/cypress/issues/8008#issuecomment-706237084 solved both of my issues for me. But I suspect when Cypress starts using Webpack 5 and I can remove that workaround, I'll get the `babel.config.js` problem again, since using the webpack preprocessor overrides the default Babel preprocessor Cypress uses

**Comment by karltaylor** [comment]
> adding an empty `.babelrc` file to the cypress directory allowed me to work around this issue.
> i.e. `cypress/.babelrc`
> 
> ```
> {}
> ```

I am unsure why this got so many downvotes, it perfectly solved my issue.

**Comment by luanapmildner** [comment]
Hey Guys, I have this problem and I've tried to add {cypress/.babelrc} inside the cypress.json file. Should I write something else??? 
My error: Unexpected token c in JSON at position 0

**Comment by laurogripa** [comment]
> Hey Guys, I have this problem and I've tried to add {cypress/.babelrc} inside the cypress.json file. Should I write something else???
> My error: Unexpected token c in JSON at position 0

Hey! You should add it to the file to `cypress` directory, not the `cypress.json` file. The file is `cypress/.babelrc` and the content is `{}`

**Comment by luanapmildner** [comment]
Thankss laurogripa! 

> > Hey Guys, I have this problem and I've tried to add {cypress/.babelrc} inside the cypress.json file. Should I write something else???
> > My error: Unexpected token c in JSON at position 0
> 
> Hey! You should add the file to `cypress` directory, not inside `cypress.json`. The file is `cypress/.babelrc` and the content is `{}`

Thank you!!

**Comment by JCHappytime** [comment]
> adding an empty `.babelrc` file to the cypress directory allowed me to work around this issue.
> i.e. `cypress/.babelrc`
> 
> ```
> {}
> ```

Thanks for your sharing, it works for me.

<b>"cypress": "^6.6.0"</b>

**Comment by mihailthebuilder** [comment]
> adding an empty `.babelrc` file to the cypress directory allowed me to work around this issue.
> i.e. `cypress/.babelrc`
> 
> ```
> {}
> ```

Same issue, this solution worked for me as well.
```json
 "cypress": "^6.8.0"
```

**Comment by inthegarage** [comment]
I have the same issue and I can't get this working right now. I've installed the dependencies mentioned on this ticket and also the .bashrc file, but no joy. I will downgrade to the 6.6.0 version and see if that works for me.
```
./cypress/integration/sample_spec.js
Module build failed (from /home/xxx/.cache/Cypress/7.2.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):

# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
^
```
This is just using the hello world example. Some further logs:

```
Error: Webpack Compilation Error
./cypress/integration/sample_spec.js
Module build failed (from /home/xxx/.cache/Cypress/7.2.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
/home/<path to>t/browserslist:1
# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
^
```

**Comment by inthegarage** [comment]
Downgrading to 6.9.1 did not work will fix to 6.6.0 and see what happens.

**Comment by JJ** [comment]
Adding .babelrc didn't work for me. But my problem was with a .css file

**Comment by tballast** [comment]
I'm having the same issue. I used the empty `.babelrc` file for a while and it worked, however somehow now it has reverted to giving me errors. 

Initially it was all babel errors. (ie. `Can't find babel-plugin-transform-class-properties`, etc.) It went through most of my babel plugins and complained about them until I either removed them, or installed the dependency within the repo. Afterwards however, it then started to complain about failing to parse specific modules. In my particular case it's `ag-theme-balham.css` which is a stylesheet used for AG Grid. 

Cypress Version: 7.4.0
`.babelrc`
```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"]
      }
    ]
  ],
  "sourceMaps": true
}
```

And the current error that I'm getting:
```
Error: Webpack Compilation Error
./node_modules/ag-grid-community/dist/styles/ag-theme-balham.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .ag-theme-balham {
|   -webkit-font-smoothing: antialiased;
|   color: #000;
...
```
I'm also using create react app and would really prefer not to eject if possible. The empty babelrc file worked for so long, I don't understand what I've done in the meantime that changed that.

**Comment by luichooy** [comment]
I have the same issue width Cypress v7.3.0. And it has no effect that adding `cypress/.babelrc` with content `{}`.

 I have a .babelrc file in project root dir with content as below:
```
{
  "plugins": [
    "transform-vue-jsx",
    "transform-decorators-legacy",
    "add-module-exports",
    "transform-object-assign",
    [
      "transform-object-rest-spread",
      {
        "useBuiltIns": true
      }
    ]
  ],
  "presets": ["env", "es2015", "stage-2"]
}
```

The error message is:
![image](https://user-images.githubusercontent.com/26423033/120784750-00263100-c55f-11eb-8086-714f821a4da2.png)

**Comment by luichooy** [comment]
I have the same issue width Cypress v7.3.0. And it has no effect that adding `cypress/.babelrc` with content `{}`.

 I have a .babelrc file in project root dir with content as below:
```
{
  "plugins": [
    "transform-vue-jsx",
    "transform-decorators-legacy",
    "add-module-exports",
    "transform-object-assign",
    [
      "transform-object-rest-spread",
      {
        "useBuiltIns": true
      }
    ]
  ],
  "presets": ["env", "es2015", "stage-2"]
}
```

The error message is:
![image](https://user-images.githubusercontent.com/26423033/120784750-00263100-c55f-11eb-8086-714f821a4da2.png)
