### ISSUE TITLE
Error: Webpack Compilation Error (Module parse failed)

### ISSUE THREAD

**Issue by Roger-Fang-CS** [cypress-io/cypress#8924]
### Current behavior

![image](https://user-images.githubusercontent.com/68213939/96830673-677aef00-146e-11eb-9b54-a5e4cbd7ce28.png)

### Desired behavior

after upgrading cypress to 5.3.0, one  json file couldn't be process successfully, but other json files work well

### Versions
cypress: 5.3.0
os : windows10 64bits

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Please provide the JSON files, their content and how you are accessing them in your test file. Something we can copy/paste is ideal.

We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
