### PR TITLE
fix: fix third party reporters and cy.origin calls in Cypress

### LINKED ISSUE #24607: 11.0.0 `cypress run` -> `Error: Cannot find module 'mocha-7.0.1'`
### Current behavior

When I upgraded to 11.0.0, I ran `cypress run` as usual, and I got an error `Error: Cannot find module 'mocha-7.0.1'`

### Desired behavior

_No response_

### Test code to reproduce

const { defineConfig } = require('cypress')

module.exports = defineConfig({
  reporter: 'mochawesome',
  reporterOptions: {
    reportDir: 'cypress/results',
    overwrite: false,
    html: false,
    json: true
  }
})

### Cypress Version

11.0.0

### Node version

v16.18.0

### Operating System

macOS 13.0

### Debug Logs

```shell
[1] Error loading the reporter: mochawesome
[1] 
[1] We searched for the reporter in these paths:
[1] 
[1]  - /Users/xxx/project/mochawesome
[1]  - /Users/xxx/project/node_modules/mochawesome
[1] 
[1] Learn more at https://on.cypress.io/reporters
[1] 
[1] Error: Cannot find module 'mocha-7.0.1'
[1] Require stack:
[1] - /Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
[1]     at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
[1]     at PackherdModuleLoader._tryResolveFilename (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:645:32)
[1]     at PackherdModuleLoader._resolvePaths (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:491:31)
[1]     at PackherdModuleLoader.tryResolve (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:313:40)
[1]     at resolve (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/require.js:125:33)
[1]     at require.resolve (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/v8-snapshot-require/dist/snapshot-require.js:216:28)
[1]     at customRequire.resolve (<embedded>:2809:961257)
[1]     at <embedded>:2755:13102
[1]     at i._load (<embedded>:2750:54101)
[1]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[1]     at require (node:internal/modules/cjs/helpers:102:18)
[1]     at Object.<anonymous> (/Users/xxx/project/node_modules/.pnpm/mochawesome@7.1.3_mocha@10.1.0/node_modules/mochawesome/src/mochawesome.js:1:14)
[1]     at Module._compile (node:internal/modules/cjs/loader:1120:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
[1]     at Module.load (node:internal/modules/cjs/loader:988:32)
[1]     at Module._load (node:internal/modules/cjs/loader:829:12)
[1]     at c._load [as origLoad] (node:electron/js2c/asar_bundle:5:13339)
[1]     at PackherdModuleLoader.tryLoad (/Users/xxx/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/packherd-require/dist/loader.js:432:30)
[1]     at customRequire (<embedded>:2809:960157)
[1]     at S.loadReporter (<embedded>:2755:19452)
[1]     at P.initializeReporter (<embedded>:2802:336581)
[1]     at P.startWebsockets (<embedded>:2802:336891)
[1]     at P.open (<embedded>:2802:335033)
[1]     at async v.create (<embedded>:2802:347432)
[1]     at async O (<embedded>:2802:421364)
[1]     at async W (<embedded>:2802:432780)
```

### Other

_No response_

### LINKED ISSUE #24611: Cypress `v11.0.0` Broken with `experimentalSessionAndOrigin: true`
### Current behavior

I wanted to upgrade to cypress `v11` from `v10.4.0`. After bumping the version Cypress is broken.
Figuring out whats wrong I found that the `experimentalSessionAndOrigin: true` leads to this error which prevents cypress from running the tests

When I disable `experimentalSessionAndOrigin` tests seem to work but obviously don't pass as I use session and origin

```js
Error: Webpack Compilation Error
./cypress/tests/e2e/_userLogin.cy.ts
Module build failed (from /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/lib/cross-origin-callback-loader.js):
Error: Cannot find module '/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/parser/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at Watching.handle [as handler] (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:230:23)
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:98:28)
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:54:20
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/..../Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:179:23)
```

### experimentalSessionAndOrigin: true
Screenshot 2022-11-09 at 13 08 04

### experimentalSessionAndOrigin: false
Screenshot 2022-11-09 at 13 08 16

### Desired behavior

Cypress successfully runs the tests as normal

### Test code to reproduce

....

### Cypress Version

    "cypress": "11.0.0"

### Node version

v14.18.1

### Operating System

macOS BigSur 11.7

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #24607
- Closes #24611 

### User facing changelog

Cypress will no longer crash when using a third party reporter like `mochawesome`.

Cypress will no longer crash when using the `experimentalSessionAndOrigin` flag.

### Additional details

When cleaning up the binary due to the v8 snapshot work, there were a couple of dependencies that were removed that shouldn't have been.

In the case of third party mocha reporters, we do some swizzling at runtime with a hard coded version of mocha (mocha-7.0.1). In order to allow this to work properly, we need to leave `mocha-7.0.1` in the binary.

In the case of the `experimentalSessionAndOrigin` flag, we have a dynamically loaded loader whose dependencies were not being flagged as something that shouldn't be removed. We will ensure that these dependencies are kept by wrapping this dependency in a `require.resolve`.

### Steps to test

Run the binary with a third party reporter like `mochaawesome`

Run the binary with `experimentalSessionAndOrigin` turned on

### How has the user experience changed?

The app no longer crashes in the above scenarios.

### PR Tasks

- [X] Have tests been added/updated?
- [X] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/webpack-preprocessor/index.ts [hunk 1]
```diff
@@ -249,7 +249,7 @@ const preprocessor: WebpackPreprocessor = (options: PreprocessorOptions = {}): F
       webpackOptions.module.rules.unshift({
         test: /\.(js|ts|jsx|tsx)$/,
         use: [{
-          loader: path.join(__dirname, 'lib/cross-origin-callback-loader'),
+          loader: require.resolve('@cypress/webpack-preprocessor/dist/lib/cross-origin-callback-loader.js'),
```
Comment (emilyrohrbough) [inline npm/webpack-preprocessor/index.ts:252]: If we need to do require.resolve() within the NPM module, is there risk that custom webpack configuration will be problematic or is this only for snapshot resolution in the binary?

File: npm/webpack-preprocessor/package.json [hunk 2]
```diff
@@ -20,6 +20,7 @@
     "watch": "rimraf dist && tsc --watch"
   },
   "dependencies": {
+    "@babel/parser": "7.13.0",
```
Comment (emilyrohrbough) [inline npm/webpack-preprocessor/package.json:23]: why does this need @babel/parser?

File: npm/webpack-preprocessor/index.ts (hunk 1 above)
Comment (ryanthemanuel) [reply npm/webpack-preprocessor/index.ts:252]: This is only for snapshot resolution in the binary.

File: npm/webpack-preprocessor/package.json (hunk 2 above)
Comment (ryanthemanuel) [reply npm/webpack-preprocessor/package.json:23]: https://github.com/cypress-io/cypress/blob/ryanm/fix/improve-binary-cleanup-to-look-at-binary-rather-than-monorepo/npm/webpack-preprocessor/lib/cross-origin-callback-loader.ts#L2

File: npm/webpack-preprocessor/index.ts (hunk 1 above)
Comment (emilyrohrbough) [reply npm/webpack-preprocessor/index.ts:252]: & vite doesn't have issues because we don't ship with the binary? https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/src/resolveConfig.ts#L14

**Review by mjhenkes — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]
Binary changes seem to be working for the various scenarios I tried. 👍🏻
