### PR TITLE
chore: replace Bluebird with native promises in system-tests harness

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes N/A — purely mechanical internal tooling change with no user-facing impact. This is one step in moving the repo off Bluebird; the `system-tests/test/` specs and the `system-tests/projects/` fixtures are deliberately untouched and handled separately.

### Additional details

Converts four system-tests harness modules off Bluebird. None of these files ship to users.

**`system-tests/lib/performance.js`**
- Dropped the `bluebird` require. The single `Promise.resolve()` now uses the native global.

**`system-tests/lib/spec_helper.js`**
- Dropped the `bluebird` require and the `sinon.usingPromise(Promise)` call. Sinon already defaults to native promises, so that line became a no-op.

**`system-tests/lib/serverStub.ts`**
- `Bluebird.delay(300)` → `setTimeout` from `node:timers/promises`; the `putScreenshots` handler is now an `async` method.

**`system-tests/lib/system-tests.ts`**
- `Bluebird.map(…)` → `Promise.all(arr.map(…))`, in both `setup`'s `beforeEach` and `afterEach`.
- `new Bluebird(…)` → `new Promise(…)` in `startServer`.
- `fs.copyAsync(src, dest, …).catch({ code: 'ENOENT' }, …)` → `fs.copy(…)` with an explicit `err.code !== 'ENOENT'` rethrow. `fs-extra` 9.1.0 already returns a native promise when no callback is passed, so the `Async` suffix is unnecessary.
- Removed `cp = Bluebird.promisifyAll(cp)` and changed `let cp` to `const cp`. Nothing in the file called a `*Async` `child_process` method — only `cp.spawn` — so no `util.promisify` wrapper was needed.
- Removed `Bluebird.config({ longStackTraces: true })`.

`stopServer` was left alone: `destroyAsync` comes from `@packages/server`'s `allowDestroy`, which already builds it with `util.promisify`.

**Notes for reviewers**

`bluebird` remains a dependency of `@tooling/system-tests`. It is still used by `lib/dep-installer/index.ts`, four specs under `test/`, and the fixture projects.

Removing `sinon.usingPromise` changes what `stub.resolves()` would return across the suite. Verified this is inert: there are zero `.resolves()` / `.rejects()` / `.callsFake()` calls anywhere in `system-tests/`. The only two Sinon usages are `sinon.spy(() => {…})` in `test/network_error_handling_spec.js` and `sinon.stub(process, 'exit')` in `lib/system-tests.ts`, neither of which produces a promise.

`systemTests.exec()` was already an `async` function returning a native promise before this change, so nothing chained onto it by the specs is affected.

---

> [!NOTE]
> **Low Risk**
> Internal system-test harness only; behavior-preserving promise API swaps with no auth, product runtime, or public API impact.
> 
> **Overview**
> **Removes Bluebird from the system-tests harness** in favor of native `Promise`, `Promise.all`, and `node:timers/promises`, as part of a broader repo migration. No user-facing or shipped code is touched.
> 
> In **`system-tests.ts`**, server startup/teardown uses `Promise.all` instead of `Bluebird.map`, `startServer` wraps listen in `new Promise`, artifact copying uses `fs.copy` with an explicit `ENOENT` catch (replacing Bluebird-style `.catch({ code })`), and **`Bluebird.promisifyAll(cp)`** plus **`Bluebird.config({ longStackTraces: true })`** are dropped.
> 
> **`serverStub.ts`** delays screenshot PUT responses with **`await delay(300)`** from **`node:timers/promises`** instead of **`Bluebird.delay`**. **`spec_helper.js`** drops the Bluebird import and **`sinon.usingPromise(Promise)`** (Sinon already uses native promises). **`performance.js`** no longer requires Bluebird.
> 
> The e2e plugin task **`record:fast_visit_spec`** chains **`.then(() => null)`** instead of Bluebird’s **`.return(null)`** because **`performance.track`** now returns a native promise.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 829d2680b29b80fcb292a5ce0a76e3b15db6a968. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### Steps to test

These files are the harness itself, so the whole system-test suite exercises them. Targeted runs that cover each converted path:

```bash
# serverStub putScreenshots delay + the Bluebird.map server setup/teardown
cd system-tests && node ./scripts/run.js --glob-in-dir="record"

# screenshot upload path through the stubbed server
cd system-tests && node ./scripts/run.js --glob-in-dir="screenshot"
```

Static checks that were run locally:

- `eslint` on all four changed files — clean.
- `tsc --project system-tests` before and after — identical error sets apart from two line-number shifts caused by the one deleted line in `serverStub.ts`. (Remaining errors are pre-existing artifacts of an unbuilt monorepo in the sandbox: missing generated `fixtureDirs`, `cloudValidations`, and `@packages/*` declarations.)

Worth noting: `test-binary/` specs also load `lib/spec_helper.js` and `lib/system-tests.ts`, and those jobs run in the main workflows rather than on a PR branch. If reviewers want the binary jobs to cover this, the branch would need adding to the full-CI allowlist in `.circleci/src/pipeline/workflows/@main.yml` — I did not do that unilaterally, since it widens CI considerably.

### How has the user experience changed?

No change. These are internal test-tooling files that are not published and do not ship in the Cypress binary.

### PR Tasks

- [na] Is there an associated issue with maintainer approval for PR submission? 
- [na] Have tests been added/updated? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)? 

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01YT18Hyu662Zwac38zWDp6U

---
_Generated by [Claude Code](https://claude.ai/code/session_01YT18Hyu662Zwac38zWDp6U)_

### CODE REVIEW

File: system-tests/lib/performance.js [hunk 1]
```diff
@@ -1,7 +1,6 @@
 const ciProvider = require('@packages/server/lib/util/ci_provider')
 const { commitInfo } = require('@packages/server/lib/util/commit-info')
 const pkg = require('@packages/root')
-const Promise = require('bluebird')
```
[the remark this answers is not in the document]
Comment (jennifer-shehane) [reply system-tests/lib/performance.js:4]: Good catch — this was a real regression, now fixed in 829d268.

I had verified the callers of `performance.track()` before opening the PR, but my search covered `lib/`, `test/`, `test-binary/` and `scripts/` and excluded `projects/`, so this cross-boundary caller slipped through.

Confirmed the failure directly:

```
$ node -e "require('@packages/ts/register'); const p = require('./lib/performance').track('x', {}); ..."
has .return(): undefined
is native Promise: true
```

So `.return(null)` would have thrown `TypeError: ... is not a function` and taken `cy.task('record:fast_visit_spec')` down with it.

The fix changes the one coupled line in `system-tests/projects/e2e/cypress/plugins/index.js`:

```js
return performance.track('fast_visit_spec percentiles', data)
.then(() => null)
```

That resolves to `null` on both shapes the task can see — the real native-promise `track()`, and the Bluebird `track: () => Promise.resolve()` fallback stub used when the require fails in open mode.

Worth noting for scope: `projects/` fixtures are intentionally left on Bluebird in this PR, and this file still uses it in three other places, so its user-land Bluebird coverage is intact. Only the call site coupled to the harness's promise type changed.

I also re-swept `projects/` for any other importer of the four converted harness modules — `lib/performance` here is the only one. The other `@tooling/system-tests` imports from fixtures all point at `lib/pluginUtils`, which this PR does not touch.

---
_Generated by [Claude Code](https://claude.ai/code)_
