### ISSUE TITLE
Webpack compilation error after upgrade from v12+ to v14+

### ISSUE THREAD

**Issue by fleks-dev** [cypress-io/cypress#31146]
### Current behavior

I was using `12.11.0`, then I've upgraded to `v14.0.3`, and experienced this error.

I've narrowed it down to `v12.17.4`. I followed the instruction in the [Changelog](https://docs.cypress.io/app/references/changelog#12-17-4), but with no success so far.

Cypress webpack preprocessor throws these errors for each `.png`, `.pdf`, and `.mp4` asset I have present in my `fixtures` directory.

### Desired behavior

All media assets should load like they did before `v12.17.4`, before webpack `v5`

### Test code to reproduce

```sh
# Fixtures directory
- any.png
```

```js
# package.json
{
  ...
  "devDependencies": {
    ...
    "cypress": "14.0.3",
  },
}

```

### Cypress Version

v12.17.4

### Node version

v20.10.0

### Operating System

Windows/OSX

### Debug Logs

```shell
Webpack Compilation Error
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> %PDF-1.3
| %����
|

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

**Comment by fleks-dev** [comment]
@jennifer-shehane Can someone look into this?

Problem is that I can't have any images inside of the `fixtures/` directory, and I can't see nowhere a workaround for this.

**Comment by fleks-dev** [comment]
Would love to upgrade, but can't.
