### ISSUE TITLE
browserslist not work in cypress 7.1.0 for  angular program

### ISSUE THREAD

**Issue by shangzhouwan** [cypress-io/cypress#16083]
Current behavior
I get the error when trying to run tests through the Runner:

> Error: Webpack Compilation Error
./cypress/integration/login_spec.js
Module build failed (from /Users/xu/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/babel-loader/lib/index.js):
/Users/xu/workspace/main/browserslist:1

` # This file is used by the build system to adjust CSS and JS output to support the specified browsers below.`

Versions
Cypress: 7.10.0
Mac OS: 10.15.7 
Node: 12.16.1

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
