### ISSUE TITLE
Cypress 3.8.1 and up: Error TS8020: JSDoc types can only be used inside documentation comments

### ISSUE THREAD

**Issue by Postavshik** [cypress-io/cypress#6794]
### Current behavior:

Starting from version 3.8.1, having issues in chai node modules.
![image](https://user-images.githubusercontent.com/21285622/77114774-1fd54600-69fb-11ea-99b1-c3e1343491d0.png)

```
 Error: TypeScript error: node_modules/cypress/types/chai/index.d.ts(122,9): Error TS8020: JSDoc types can only be used inside documentation comments.
```

Cypress 3.8.0 works just fine

### Versions
Cypress: 3.8.1 and up to 4.2.0
macOS Mojave v10.14.0
Node: 10.14.0

**Comment by jennifer-shehane** [comment]
Can you provide the test code you are running to reproduce this? Thanks!

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by ravalibusetty1991** [comment]
Hi @jennifer-shehane @Postavshik Did you find the solution to this? I'm seeing the same error after upgrading to 4.7.0, it works fine on 3.8.1. Any help is appreciated. Thanks!!
