### ISSUE TITLE
Close button not working on Choose browser page v13.6.4

### ISSUE THREAD

**Issue by sirkkalap** [cypress-io/cypress#28852]
### Current behavior

Clicking close button closes the browser but relaunches it immediately after closing it.

### Desired behavior

Browser should stay closed after clicking Close button.

### Test code to reproduce

The issue is in the UI and reproduced by MikeMC399 and cy.david in discord [1].

[1] https://discord.com/channels/755913899261296641/1202942184542965823

### Cypress Version

v13.6.4

### Node version

v18.7.1

### Operating System

MacOS Sonoma 14.3 (23D56)

### Other

The issue was not present at 13.6.2 according to discussion at discord (see above).

**Comment by MikeMcC399** [comment]
This is a regression from [cypress@13.6.3](https://docs.cypress.io/guides/references/changelog#13-6-3).

Reproducible also on Ubuntu 22.04 and Windows 11 with Node.js `20.11.0`.

Repro steps:

```shell
npx cypress open --e2e --browser electron
```

Then hit Close button.

**Comment by jennifer-shehane** [comment]
I can't recreate this on Mac Sonoma. Someone on our team did experience though, we thought it was a fluke, but I guess not.

**Comment by mschile** [comment]
I was able to reproduce the issue and tracked it down to being introduced in commit https://github.com/cypress-io/cypress/commit/cdc42b996f25d39e68cc562f51921098922b2f05.

**Comment by MikeMcC399** [comment]
@mschile 

> I was able to reproduce the issue and tracked it down to being introduced in commit [cdc42b9](https://github.com/cypress-io/cypress/commit/cdc42b996f25d39e68cc562f51921098922b2f05).

- Good to hear that you have tracked this down! It seems that the commit comes from https://github.com/cypress-io/cypress/pull/27795. This PR was not mentioned in the [Changelog](https://docs.cypress.io/guides/references/changelog) anywhere.

**Comment by elevatebart** [comment]
@mschile can you share the steps? Machine? Browser? I want to have a look at this issue I introduced.

Own my mistakes...

**Comment by MikeMcC399** [comment]
@elevatebart 

> can you share the steps? Machine? Browser? I want to have a look at this issue I introduced.

See https://github.com/cypress-io/cypress/issues/28852#issuecomment-1924301434 above for repro steps.

**Comment by elevatebart** [comment]
### What happens

When one clicks on the close Button, it has the wrong button type so, after closing the browser, the click re-submits the form, re-opening it. 

Why does it re-submit now while before this change everything was fine? Html buttons have `type="submit"` by default. and version 0.11.0 of the design system does not implement the type attribute properly.

### Why it happened

I made sure the bug was fixed in the design system and was implemented in full in my branch before moving the PR out of draft, but I expect that a bad merge rolled back the dependency to the button. As of now, the app and the launchpad still use 2 different version of the button. They are both outdated and with documented issues.

### How to fix

Update both dependency numbers to the latest version (see #28860)

### How to avoid it happening again

Add a **component test** to check that each button triggers the right event and only the right event.

**Comment by MikeMcC399** [comment]
I checked with the pre-release version from https://github.com/cypress-io/cypress/commit/4b6cafa86d600ddb547220482027d3e1a78d4c49#comments on Ubuntu 22.04 x64 and the fix looks fine. 🎉
