### ISSUE TITLE
The mouse click no longer works since the new version 4.3.0

### ISSUE THREAD

**Issue by GregorBiswanger** [cypress-io/cypress#6907]
I have installed the latest update with version 4.3.0 and the tests no longer run because the mouse click is no longer triggered. This is the following page: [rxjs-fruits.com](https://www.rxjs-fruits.com)

![image](https://user-images.githubusercontent.com/7336300/78125123-e0eabb80-7410-11ea-93a6-2552899455e7.png)

This is a small test of it that no longer works:

```js
  it('should success on valid solution', () => {
    cy.get('[style="top:26px;height:26px;"]').type('conveyorBelt.subscribe();');
    cy.get('#subscribeButton').click();

    cy.get('#nextButton').should('not.have.attr', 'disabled');
  });
```

The test steps indicate that you clicked, but the logic is not executed. An acceptance test shows that it works.

What can that be?

### Versions

- Windows 10
- Cypress 4.3.0
- Chrome 80

**Comment by jennifer-shehane** [comment]
I am able to reproduce this with the following code, but I am unable to find a version of Cypress that this was previously working in - tried back to Cypress 3.6.0. 

@GregorBiswanger Can you confirm that if you roll back to a previous version that this test works? What version? Or was there perhaps another change in your code base in that time?

```js
it('Test', () => {
  cy.visit('https://www.rxjs-fruits.com/')
  cy.get('.view-lines').last()
    .type('conveyorBelt.subscribe()')
  cy.get('#subscribeButton').click()
  cy.get('#nextButton').should('have.class', 'disabled')
})
```

I can also see that this is not occurring outside of Cypress tests when you manually click the button (although it is also not working inside Cypress tests if I manually click the button). 

## Outside of Cypress

![](http://g.recordit.co/2rTmZeBnUB.gif)

## Inside Cypress

![](http://g.recordit.co/B3lRR9MUu1.gif)

There is an error being thrown in the console within Cypress when the click occurs (manually or through Cypress)

```
/main-es2015.398ac8257d10455c41c1.js:1 ERROR TypeError: Cannot read property 'querySelectorAll' of null
    at AppComponent.startConveyorBeltAnimation (/main-es2015.398ac8257d10455c41c1.js:1)
    at AppComponent.run (/main-es2015.398ac8257d10455c41c1.js:1)
    at /main-es2015.398ac8257d10455c41c1.js:1
    at zr (/main-es2015.398ac8257d10455c41c1.js:1)
    at o (/main-es2015.398ac8257d10455c41c1.js:1)
    at HTMLButtonElement.<anonymous> (/main-es2015.398ac8257d10455c41c1.js:1)
    at l.invokeTask (/polyfills-es2015.e16abf3a17e45d862eec.js:1)
    at Object.onInvokeTask (/main-es2015.398ac8257d10455c41c1.js:1)
    at l.invokeTask (/polyfills-es2015.e16abf3a17e45d862eec.js:1)
    at i.runTask (/polyfills-es2015.e16abf3a17e45d862eec.js:1)
```

Looks like `querySelectorAll` cannot be read here because it is trying to read it off of `contentDocument`. I'm not sure why `contentDocument` would be used here at all. The definition of `contentDocument` is below. 

>If the iframe and the iframe's parent document are Same Origin, returns a Document (that is, the active document in the inline frame's nested browsing context), else returns null.

So, yes, this will return `null` when run within Cypress.

**Comment by GregorBiswanger** [comment]
okay, I have now rolled back to the last version 4.2.0 and get the same error... really strange, since I haven't changed anything in the actual code... I also checked the github history... contentDocument is needed to access SVG elements...

It would be interesting to know why it works in the standard browser and not with cypress ..

Thank you very much for your advice and your great commitment..

**Comment by GregorBiswanger** [comment]
Now I found the following article that helped me:
https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/

I just had to deactivate `chromeWebSecurity` in `cypress.json`.

```
{
  "chromeWebSecurity": false
}
```

It would be interesting to know why it worked before... Anyway, now the test is running and even the animation is running.. so the value is no longer zero..

Many thanks again for the quick excellent support! I love Cypress... 🥰
